// ---------------------------------------------------------------------------
// BLOG — posts and translations
// All content for /blog and /blog/:slug lives here.
// Edit titles, excerpts and body blocks freely. Body blocks support:
//   { type: 'p', text: '...' }            — paragraph
//   { type: 'h2', text: '...' }           — section heading
//   { type: 'list', items: ['..', '..'] } — bullet list
//   { type: 'callout', text: '...' }      — highlighted box (gold)
//   { type: 'quote', text: '...' }        — italic quote / signature
//   { type: 'cta', text: '...', href: '...' } — gold CTA button
// ---------------------------------------------------------------------------

// ⚠️ Replace this with your real Emergent affiliate link
export const EMERGENT_AFFILIATE = 'https://app.emergent.sh/register?ref=tony375739';

export const BLOG_PAGE = {
  cs: {
    kicker: 'Zápisky',
    title: 'Co píšu,\nco žiju.',
    subtitle:
      'Pomalé poznámky z místa, kde se kořeny potkávají s kódem. Texty o nástrojích, o životě se zvířaty, o spojení toho zdánlivě nespojitelného.',
    readTime: 'min čtení',
    back: '← Zpět na úvod',
    backToList: '← Zpět na všechny zápisky',
    publishedOn: 'Publikováno',
    share: 'Sdílet',
  },
  en: {
    kicker: 'Notes',
    title: 'What I write,\nwhat I live.',
    subtitle:
      'Slow notes from a place where roots meet code. On tools, life with animals, and joining the seemingly unjoinable.',
    readTime: 'min read',
    back: '← Back home',
    backToList: '← Back to all notes',
    publishedOn: 'Published',
    share: 'Share',
  },
  ru: {
    kicker: 'Заметки',
    title: 'Что пишу,\nчем живу.',
    subtitle:
      'Медленные заметки оттуда, где корни встречают код. О инструментах, о жизни с животными и о соединении того, что кажется несоединимым.',
    readTime: 'мин чтения',
    back: '← На главную',
    backToList: '← Ко всем заметкам',
    publishedOn: 'Опубликовано',
    share: 'Поделиться',
  },
};

export const POSTS = [
{
  id: 'loukada-prijdte-na-louku',
  slug: 'loukada-prijdte-na-louku',
  date: '2026-05-02',
  accent: '#7ab648',
  readTime: 7,
  category: { cs: 'Příroda', en: 'Nature', ru: 'Природа' },
  title: {
    cs: 'Loukáda: Přijďte na louku, kde práce chutná jinak',
    en: 'Loukáda: Come to the meadow where work tastes different',
    ru: 'Loukáda: Приходите на луг, где работа ощущается иначе',
  },
  excerpt: {
    cs: 'Příští víkend otevíráme Louku pro všechny, kdo chtějí přiložit ruku k dílu. Pomazlit Yakula, pohladit krávu, popovídat si u práce. Jednoduše přijít.',
    en: 'Next weekend we open the meadow to everyone who wants to lend a hand. Pet Yakul, stroke a cow, talk while working. Simply come.',
    ru: 'В следующие выходные мы открываем луг для всех, кто хочет помочь руками. Погладить Якула, почесать корову, поговорить за работой. Просто приехать.',
  },
  body: {
    cs: [
      { type: 'p', text: 'Ráno na Louce začíná dřív, než se probudí většina lidí. Ještě před první kávou je potřeba zkontrolovat ohrady, přinést seno, nakrmit prasíky. Krávy stojí klidně ve svém rytmu, ovce komentují příchod hlasitě a bez zábran, psi se protahují ve zlatém světle. A někde mezi tím vším se motá malá, trochu nejistá, trochu zvědavá figurka — náš mufloní mláďák Yakul.' },
      { type: 'p', text: 'Tenhle rytmus je tady každý den. Bez výjimky, bez přerušení.' },
      { type: 'p', text: 'Ale jednou za čas se otevře i pro ostatní.' },
      { type: 'h2', text: 'Co je Loukáda?' },
      { type: 'p', text: 'Není to festival. Není to přednáška. Není to akce s programem a časovým harmonogramem.' },
      { type: 'p', text: 'Je to jednoduché: přijdete, vezmete vidle nebo lopatu, pomůžete tam, kde je třeba — a u toho se dá povídat. O zvířatech. O tom, co vás zajímá. O životě, o přírodě, o tom, co koho zrovna zaměstnává. Práce rukama totiž něco dělá s hlavou. Uvolňuje ji. Vytváří prostor, ve kterém se přirozeně mluví jinak než v komentářích na sociálních sítích nebo za stolem v kanceláři.' },
      { type: 'p', text: 'A pokud si při tom necháte přiběhnout k ruce mazlivou Atilku, otřít o nohu spokojenou kočku nebo přijde blíž mufloní mládě a začne zkoumat vaše boty — tím lépe.' },
      { type: 'h2', text: 'Příští víkend u nás na Louce' },
      { type: 'p', text: 'Zveme vás na Louku, kde projekt Nech mě růst každý den reálně žije — ne jen na obrazovce, ale ve fyzickém světě, ve špíně, v trávě, v péči o zvířata, která tady jsou a která potřebují pozornost a práci.' },
      { type: 'p', text: 'Přijďte pomoci. Přivezete-li sebou ještě nějaké dobroty — pro sebe, pro ostatní, případně vhodné pamlsky pro zvířata — budeme samozřejmě rádi. Ale není to podmínka. Podmínka je jen jedno: přijít s chutí být chvíli jinde, než jste zvyklí.' },
      { type: 'h2', text: 'Co vás čeká' },
      { type: 'p', text: 'Mufloní mládě Yakul. Jeden malý muflon. Maličký, roztomilý a stále ještě trochu překvapený světem, do kterého přišel. Sledovat ho je samo o sobě důvod přijet. Je v něm ta zvláštní směs plachosti a zvědavosti, která patří k mláďatům — přijde blíž, zastaví se, odskočí, vrátí se. Pokud máte trpělivost a zůstanete klidní, možná vás přijde očichat. A to je zážitek, který se těžko popisuje.' },
      { type: 'p', text: 'Krávy. Velcí, klidní tvorové s neuvěřitelnou pamětí na lidi. Jakmile vás poznají, zůstanou stát a nechají se pohladit. Jejich klid je nakažlivý. Lidé, kteří přišli na Loukádu poprvé, mi říkali, že stání vedle krávy je jedním z nejklidnějších zážitků, jaké zažili — a přitom to vůbec nečekali.' },
      { type: 'p', text: 'Ovce. Hlučné, zvídavé a překvapivě sociální. Mají svá pravidla, svou hierarchii, své oblíbené i neoblíbené. Chvíli je pozorovat ve stádě je jako číst knihu napsanou jazykem, který sice neznáte, ale nějak mu začnete rozumět.' },
      { type: 'p', text: 'Psi a kočky. Ti jsou všude. Vždy. Vracejí lásku přímo a bez podmínek.' },
      { type: 'h2', text: 'Proč to děláme?' },
      { type: 'p', text: 'Projekt Nech mě růst je v jádru jednoduchý: věříme, že kontakt s přírodou a se zvířaty dává životu jiný rozměr. Že fyzická práce má hodnotu, která se nedá plně nahradit. Že ticho Louky je vzácné a stojí za to ho chránit — a sdílet.' },
      { type: 'p', text: 'Loukáda není o vzdělávání ani o šíření žádné filozofie. Je to pracovní setkání s lidskou tváří. Přijdete, zapracujete, potkáte lidi, potkáte zvířata, sníte něco dobrého. To je celý plán.' },
      { type: 'p', text: 'A protože každý z nás žije trochu jiný život a zajímají ho jiné věci — někdo přijde z města, někdo z přírody, někdo řeší farmaření, někdo digitální svět, někdo prostě hledá pěkné odpoledne mimo obvyklé prostředí — témata rozhovorů vznikají sama. Nikdo je neurčuje předem.' },
      { type: 'h2', text: 'Louka jako jiný čas' },
      { type: 'p', text: 'Existuje něco, co se naučíte jen tehdy, když pracujete rukou vedle živého tvora.' },
      { type: 'p', text: 'Mufloní mládě se nezajímá, jestli jste produktivní. Kráva neví, jestli máte splněné úkoly. Ovce vám nedají zpětnou vazbu na váš výkon.' },
      { type: 'p', text: 'Ale reagují na vaši přítomnost. Na to, jak se pohybujete, jak mluvíte, jak dýcháte. V tom je tichá lekce, která se jinak těžko získá — naučit se být tam, kde právě jste.' },
      { type: 'p', text: 'Louka má svůj vlastní čas. A pokud se mu podřídíte, i jen na jeden den, vrátíte se domů zcela klidní.' },
      { type: 'h2', text: 'Praktické informace' },
      { type: 'p', text: 'Přijďte příští víkend. Oblečte si něco, co se může zašpinit. Vezměte sebou dobrou náladu a případně něco dobrého k jídlu nebo pití pro společnou pauzu — tohle vždycky potěší.' },
      { type: 'callout', text: 'Pokud chcete přivézt pamlsky pro zvířata, ideální volbou je OvoZel z farmy Jamboz, která sídlí nedaleko. Více na www.jamboz.cz' },
      { type: 'p', text: 'Loukáda není velká věc. Je to jedno odpoledne, možná celý den. Lidé přijdou, zapracují, popovídají, odejdou. Zvířata zůstanou — jako vždy.' },
      { type: 'p', text: 'Ale taková setkání mají váhu, která se jinak těžko nachází. Sdílená práce, fyzická přítomnost, kontakt se zvířaty, s půdou, s rytmem, který neřídíme my — to si neseme dál, i když si to v tu chvíli neuvědomujeme.' },
      { type: 'p', text: 'Projekt Nech mě růst existuje, protože věříme, že tohle má smysl. Že Louka je místo, kam se vyplatí přijít. Že mufloní mládě, které vám přijde oňuchat ruku, vám toho řekne víc než ledajaký víkendový kurz.' },
      { type: 'quote', text: 'Uvidíme se na Louce.' },
    ],
    en: [
      { type: 'p', text: 'Morning on the meadow starts before most people wake up. Before the first coffee there are fences to check, hay to carry, piglets to feed. The cows stand calm in their rhythm, the sheep announce your arrival loudly and without restraint, the dogs stretch in golden light. And somewhere in the middle of all this wanders a small, slightly uncertain, slightly curious figure — our mouflon fawn Yakul.' },
      { type: 'p', text: 'This rhythm is here every day. Without exception, without interruption.' },
      { type: 'p', text: 'But once in a while, it opens up for others too.' },
      { type: 'h2', text: 'What is Loukáda?' },
      { type: 'p', text: 'It is not a festival. Not a lecture. Not an event with a schedule and a programme.' },
      { type: 'p', text: 'It is simple: you come, pick up a pitchfork or a shovel, help where it is needed — and along the way, there is talking. About animals. About what interests you. About life, nature, whatever is on your mind. Working with your hands does something to your head. It loosens it. It creates a space where conversation flows differently than in comment sections or behind office desks.' },
      { type: 'p', text: 'And if a dog trots up to your hand, a cat rubs against your leg, or the mouflon fawn comes over to inspect your boots — all the better.' },
      { type: 'h2', text: 'Next weekend, here at the meadow' },
      { type: 'p', text: 'We invite you to the meadow where the Nech mě růst project lives every day — not just on a screen, but in the physical world, in the mud, in the grass, in the care of animals who are here and who need attention and work.' },
      { type: 'p', text: 'Come and help. If you bring something good — for yourself, for others, or some suitable treats for the animals — we will be glad. But it is not a requirement. The only requirement is to arrive with a willingness to be somewhere different for a while.' },
      { type: 'h2', text: 'What awaits you' },
      { type: 'p', text: 'Mouflon fawn Yakul. One small mouflon. Tiny, adorable, and still slightly surprised by the world he arrived into. Watching him is reason enough to come. He carries that particular mix of shyness and curiosity that belongs to young animals — he approaches, stops, darts away, comes back. If you are patient and stay calm, he might come over to sniff your hand. That is an experience that is hard to put into words.' },
      { type: 'p', text: 'Cows. Large, calm creatures with an extraordinary memory for people. Once they know you, they will stand still and let themselves be stroked. Their calm is contagious. People who came to Loukáda for the first time told me that standing beside a cow was one of the most peaceful experiences they had had — and they had not expected anything like it.' },
      { type: 'p', text: 'Sheep. Loud, curious, and surprisingly social. They have their own rules, their own hierarchy, their own favourites. Watching them in the flock for a while is like reading a book written in a language you do not know, but somehow begin to understand.' },
      { type: 'p', text: 'Dogs and cats. They are everywhere. Always. They return love directly and without conditions.' },
      { type: 'h2', text: 'Why do we do this?' },
      { type: 'p', text: 'The Nech mě růst project is simple at its core: we believe that contact with nature and animals gives life a different dimension. That physical work has a value that cannot be fully replaced. That the silence of the meadow is rare and worth protecting — and sharing.' },
      { type: 'p', text: 'Loukáda is not about education or spreading any philosophy. It is a working gathering with a human face. You come, you work, you meet people, you meet animals, you eat something good. That is the whole plan.' },
      { type: 'p', text: 'And because each of us lives a slightly different life and is interested in different things — someone comes from the city, someone from the countryside, someone thinks about farming, someone about the digital world, someone simply wants a nice afternoon outside their usual environment — the topics of conversation arise on their own. Nobody sets them in advance.' },
      { type: 'h2', text: 'The meadow as a different kind of time' },
      { type: 'p', text: 'There is something you only learn when you work by hand beside a living creature.' },
      { type: 'p', text: 'The mouflon fawn does not care whether you are productive. The cow does not know if your tasks are done. The sheep will not give you feedback on your performance.' },
      { type: 'p', text: 'But they respond to your presence. To how you move, how you speak, how you breathe. There is a quiet lesson in that, hard to find elsewhere — learning to be where you actually are.' },
      { type: 'p', text: 'The meadow has its own time. And if you give yourself over to it, even for just one day, you will return home entirely calm.' },
      { type: 'h2', text: 'Practical information' },
      { type: 'p', text: 'Come next weekend. Wear something that can get dirty. Bring good spirits and perhaps something to eat or drink for a shared break — that always goes down well.' },
      { type: 'callout', text: 'If you would like to bring treats for the animals, a great choice is OvoZel from the nearby Jamboz farm. More at www.jamboz.cz' },
      { type: 'p', text: 'Loukáda is not a big thing. It is one afternoon, maybe a whole day. People come, they work, they talk, they leave. The animals stay — as always.' },
      { type: 'p', text: 'But such gatherings carry a weight that is hard to find elsewhere. Shared work, physical presence, contact with animals, with soil, with a rhythm we do not control — we carry that with us, even if we do not notice it at the time.' },
      { type: 'p', text: 'The Nech mě růst project exists because we believe this matters. That the meadow is a place worth coming to. That the mouflon fawn who comes to sniff your hand will tell you more than any weekend workshop.' },
      { type: 'quote', text: 'See you on the meadow.' },
    ],
    ru: [
      { type: 'p', text: 'Утро на лугу начинается раньше, чем просыпается большинство людей. Ещё до первого кофе нужно проверить ограды, принести сено, покормить поросят. Коровы стоят спокойно в своём ритме, овцы громко комментируют приход — без стеснения, собаки потягиваются в золотом свете. А где-то среди всего этого копошится маленькая, чуть неуверенная, чуть любопытная фигурка — наш муфлончик Якул.' },
      { type: 'p', text: 'Этот ритм здесь каждый день. Без исключений, без перерывов.' },
      { type: 'p', text: 'Но раз в какое-то время он открывается и для других.' },
      { type: 'h2', text: 'Что такое Loukáda?' },
      { type: 'p', text: 'Это не фестиваль. Не лекция. Не мероприятие с программой и расписанием.' },
      { type: 'p', text: 'Всё просто: приезжаете, берёте вилы или лопату, помогаете там, где нужно — и по ходу дела разговариваете. О животных. О том, что вас интересует. О жизни, о природе, о том, что сейчас занимает. Работа руками делает что-то с головой. Освобождает её. Создаёт пространство, в котором говорится иначе, чем в комментариях в соцсетях или за офисным столом.' },
      { type: 'p', text: 'А если при этом к руке прибежит ласковая Атилка, кошка потрётся о ногу или муфлончик подойдёт поближе и начнёт изучать ваши ботинки — тем лучше.' },
      { type: 'h2', text: 'Следующие выходные — у нас на лугу' },
      { type: 'p', text: 'Приглашаем вас на луг, где проект Nech mě růst живёт каждый день по-настоящему — не только на экране, а в физическом мире, в грязи, в траве, в заботе о животных, которые здесь есть и которым нужны внимание и труд.' },
      { type: 'p', text: 'Приезжайте помочь. Если привезёте с собой что-нибудь вкусное — для себя, для других, или подходящие лакомства для животных — будем рады. Но это не обязательно. Обязательно одно: приехать с желанием побыть немного в другом месте, чем обычно.' },
      { type: 'h2', text: 'Что вас ждёт' },
      { type: 'p', text: 'Муфлончик Якул. Один маленький муфлон. Крошечный, милый и всё ещё немного удивлённый миром, в который пришёл. Наблюдать за ним — само по себе повод приехать. В нём та особая смесь робости и любопытства, которая свойственна детёнышам: подходит ближе, останавливается, отскакивает, возвращается. Если у вас есть терпение и вы остаётесь спокойны — возможно, он придёт вас обнюхать. Это ощущение трудно описать словами.' },
      { type: 'p', text: 'Коровы. Большие, спокойные существа с невероятной памятью на людей. Как только они вас узнают, стоят смирно и позволяют себя погладить. Их спокойствие заразительно. Те, кто приезжал на Loukáda впервые, говорили мне, что постоять рядом с коровой — один из самых умиротворяющих опытов в их жизни. И они совсем этого не ожидали.' },
      { type: 'p', text: 'Овцы. Шумные, любопытные и удивительно социальные. У них свои правила, своя иерархия, свои любимцы и нелюбимцы. Понаблюдать за ними в стаде — всё равно что читать книгу на языке, которого вы не знаете, но почему-то начинаете понимать.' },
      { type: 'p', text: 'Собаки и кошки. Они везде. Всегда. Отдают любовь прямо и без условий.' },
      { type: 'h2', text: 'Зачем мы это делаем?' },
      { type: 'p', text: 'Проект Nech mě růst в основе своей прост: мы верим, что контакт с природой и животными придаёт жизни другое измерение. Что физический труд имеет ценность, которую нельзя полностью заменить. Что тишина луга редка и её стоит беречь — и делиться ею.' },
      { type: 'p', text: 'Loukáda — не про образование и не про распространение какой-либо философии. Это рабочая встреча с человеческим лицом. Приедете, поработаете, познакомитесь с людьми и животными, съедите что-нибудь вкусное. Вот и весь план.' },
      { type: 'p', text: 'А поскольку каждый из нас живёт немного по-своему и интересуется разным — кто-то приедет из города, кто-то из деревни, кто-то занимается фермерством, кто-то цифровым миром, кто-то просто ищет хороший день вне привычной обстановки — темы разговоров возникают сами. Никто не назначает их заранее.' },
      { type: 'h2', text: 'Луг как другое время' },
      { type: 'p', text: 'Есть кое-что, чему учишься только тогда, когда работаешь руками рядом с живым существом.' },
      { type: 'p', text: 'Муфлончику всё равно, продуктивны ли вы. Корова не знает, выполнены ли ваши задачи. Овцы не дадут вам обратной связи по вашей эффективности.' },
      { type: 'p', text: 'Но они реагируют на ваше присутствие. На то, как вы двигаетесь, как говорите, как дышите. В этом есть тихий урок, который иначе трудно получить — научиться быть там, где ты сейчас есть.' },
      { type: 'p', text: 'У луга своё время. И если вы ему подчинитесь, хотя бы на один день, вернётесь домой совершенно спокойными.' },
      { type: 'h2', text: 'Практическая информация' },
      { type: 'p', text: 'Приезжайте в следующие выходные. Оденьте что-нибудь, что можно испачкать. Возьмите с собой хорошее настроение и, если хотите, что-нибудь вкусное для общей паузы — это всегда радует.' },
      { type: 'callout', text: 'Если хотите привезти лакомства для животных — отличный вариант OvoZel с фермы Jamboz, которая находится неподалёку. Подробнее на www.jamboz.cz' },
      { type: 'p', text: 'Loukáda — не большое дело. Это один день, может быть полдня. Люди приедут, поработают, поговорят, уедут. Животные останутся — как всегда.' },
      { type: 'p', text: 'Но такие встречи имеют вес, который иначе трудно найти. Общий труд, физическое присутствие, контакт с животными, с землёй, с ритмом, которым не управляем мы — это остаётся с нами, даже если мы не осознаём этого в тот момент.' },
      { type: 'p', text: 'Проект Nech mě růst существует, потому что мы верим: это имеет смысл. Что луг — место, куда стоит приехать. Что муфлончик, который придёт обнюхать вашу руку, скажет вам больше, чем любой выездной семинар.' },
      { type: 'quote', text: 'Увидимся на лугу.' },
    ],
  },
},
  
  {
    id: 'emergent-prompting',
    slug: 'emergent-jak-spravne-promptovat',
    date: '2026-05-01',
    accent: '#9ae66e',
    readTime: 6,
    category: { cs: 'Nástroje', en: 'Tooling', ru: 'Инструменты' },
    title: {
      cs: 'Jak (skutečně) promptovat v Emergentu',
      en: 'How to (actually) prompt in Emergent',
      ru: 'Как (по-настоящему) промптить в Emergent',
    },
    excerpt: {
      cs: 'Emergent staví aplikace přímo z dialogu. Když mu mluvíš jako řemeslníkovi, postaví ti dílo. Tady je můj postup — a proč teď stojí jen dolar.',
      en: 'Emergent builds apps from conversation. Speak to it like a craftsman, and it will craft. Here is my way — and why it now costs just a dollar.',
      ru: 'Emergent строит приложения из диалога. Говори с ним как с мастером — и он построит. Вот мой способ — и почему он сейчас стоит всего доллар.',
    },
    body: {
      cs: [
        { type: 'p', text: 'Emergent je platforma, kde se v rozhovoru s AI rodí celé webové i mobilní aplikace. Já tady stavím tenhle web — a postavil bych si tu i ten příští. Není to magie. Je to pořádný řemeslník, který umí poslouchat.' },
        { type: 'h2', text: 'Co Emergent reálně umí' },
        { type: 'list', items: [
          'Frontend i backend v jedné konverzaci — React, FastAPI, MongoDB',
          'Deploy na Vercel nebo Netlify v podstatě jedním klikem',
          'Pamatuje si kontext celého projektu',
          'Refaktoruje, opravuje chyby, testuje',
          'Píše dokumentaci, README a deploy konfiguraci',
        ]},
        { type: 'h2', text: 'Jak s ním mluvit' },
        { type: 'p', text: 'Nech ho dělat to, v čem je dobrý — myslet samostatně. Tvoje práce není psát kód. Tvoje práce je vědět, co chceš. Pak to řekneš jasně, prostě a klidně. Jako řemeslníkovi, kterému věříš.' },
        { type: 'list', items: [
          'Začni vizí, ne detaily — řekni co a proč, ne jak',
          'Jeden záměr na zprávu — nemíchej tři přání dohromady',
          'Když něco selže, popiš co vidíš a co jsi čekal',
          'Schvaluj postup po krocích, ne po stovkách řádků',
          'Říkej "ne" často — AI si ráda přidá víc, než potřebuješ',
        ]},
        { type: 'h2', text: 'Cena, která dává smysl' },
        { type: 'callout', text: 'Aktuálně 1 $ / měsíc. Ano, doslova jeden dolar. Pro mě to znamená: zkus, co tě napadne. Postav. Pokus. Zahoď. Stavební papír je levný.' },
        { type: 'h2', text: 'Pojď to zkusit' },
        { type: 'p', text: 'Pokud chceš dát Emergentu šanci, použij odkaz níže — pomůžeš mi tím držet můj malý workflow naživu a sám si zahraješ s nástrojem, který opravdu staví.' },
        { type: 'cta', text: 'Otevřít Emergent', href: EMERGENT_AFFILIATE },
      ],
      en: [
        { type: 'p', text: 'Emergent is a platform where full web and mobile apps are born from a conversation with AI. I am building this site here — and I would build the next one here too. It is not magic. It is a proper craftsman who knows how to listen.' },
        { type: 'h2', text: 'What Emergent really does' },
        { type: 'list', items: [
          'Frontend and backend in one conversation — React, FastAPI, MongoDB',
          'Deploy to Vercel or Netlify in basically one click',
          'Remembers the entire project context',
          'Refactors, fixes bugs, tests',
          'Writes documentation, README and deploy config',
        ]},
        { type: 'h2', text: 'How to speak with it' },
        { type: 'p', text: 'Let it do what it is good at — thinking on its own. Your job is not to write code. Your job is to know what you want. Then say it clearly, simply, calmly. Like to a craftsman you trust.' },
        { type: 'list', items: [
          'Start with the vision, not the details — say what and why, not how',
          'One intent per message — do not mix three wishes together',
          'When something fails, describe what you see and what you expected',
          'Approve step by step, not hundreds of lines at once',
          'Say "no" often — AI loves to add more than you need',
        ]},
        { type: 'h2', text: 'A price that makes sense' },
        { type: 'callout', text: 'Currently 1 USD / month. Yes, literally one dollar. For me that means: try whatever crosses your mind. Build. Try. Throw away. The building paper is cheap.' },
        { type: 'h2', text: 'Come and try it' },
        { type: 'p', text: 'If you want to give Emergent a chance, use the link below — it helps me keep my little workflow alive and lets you play with a tool that really builds.' },
        { type: 'cta', text: 'Open Emergent', href: EMERGENT_AFFILIATE },
      ],
      ru: [
        { type: 'p', text: 'Emergent — платформа, где целые веб- и мобильные приложения рождаются из разговора с ИИ. Я строю этот сайт именно здесь — и следующий построил бы здесь же. Это не магия. Это настоящий мастер, умеющий слушать.' },
        { type: 'h2', text: 'Что Emergent реально умеет' },
        { type: 'list', items: [
          'Фронтенд и бэкенд в одном диалоге — React, FastAPI, MongoDB',
          'Деплой на Vercel или Netlify буквально в один клик',
          'Помнит контекст всего проекта',
          'Рефакторит, чинит ошибки, тестирует',
          'Пишет документацию, README и конфигурацию деплоя',
        ]},
        { type: 'h2', text: 'Как с ним говорить' },
        { type: 'p', text: 'Дай ему делать то, что он умеет — думать самостоятельно. Твоё дело не писать код. Твоё дело — знать, чего ты хочешь. И сказать это ясно, просто, спокойно. Как мастеру, которому доверяешь.' },
        { type: 'list', items: [
          'Начни с виденья, не с деталей — что и зачем, а не как',
          'Одно намерение на сообщение — не смешивай три желания',
          'Если что-то ломается, опиши что видишь и что ожидал',
          'Одобряй шаг за шагом, а не по сотням строк',
          'Говори "нет" часто — ИИ любит добавить больше, чем нужно',
        ]},
        { type: 'h2', text: 'Цена, в которой есть смысл' },
        { type: 'callout', text: 'Сейчас 1 $ / месяц. Да, буквально один доллар. Для меня это значит: пробуй всё, что приходит в голову. Строй. Пробуй. Выбрасывай. Строительная бумага дешёвая.' },
        { type: 'h2', text: 'Попробуй' },
        { type: 'p', text: 'Если хочешь дать Emergent шанс — пройди по ссылке ниже. Мне это поможет сохранить мой маленький рабочий поток, а ты поиграешь с инструментом, который действительно строит.' },
        { type: 'cta', text: 'Открыть Emergent', href: EMERGENT_AFFILIATE },
      ],
    },
  },
  {
    id: 'life-on-meadow',
    slug: 'zivot-na-louce-sto-dusi-ai-a-klid',
    date: '2026-05-01',
    accent: '#d4a45a',
    readTime: 5,
    category: { cs: 'Život', en: 'Life', ru: 'Жизнь' },
    title: {
      cs: 'Život na louce: sto duší, AI a klid',
      en: 'Life on a meadow: a hundred souls, AI, and stillness',
      ru: 'Жизнь на лугу: сто душ, ИИ и тишина',
    },
    excerpt: {
      cs: 'Žiju na louce s více než stovkou zvířat. Každý den je celodenní. A přesto mi technologie konečně začínají uvolňovat ruce.',
      en: 'I live on a meadow with more than a hundred animals. Every day is a full day. And yet, technology is finally freeing my hands.',
      ru: 'Живу на лугу с более чем сотней животных. Каждый день — на целый день. И всё-таки технологии наконец-то освобождают мои руки.',
    },
    body: {
      cs: [
        { type: 'p', text: 'Když ráno vstanu, první věc, kterou udělám, je obejít stáje. Více než sto duší — osel, ovce, muflon, slepice, husy, psi, kočky, krávy. Každá s vlastním jménem, charakterem a každodenní potřebou.' },
        { type: 'h2', text: 'Celý den krmení, voda, hlína' },
        { type: 'p', text: 'Žijeme v krajině, kterou jsme zdědili. Není to zoo, ani farma — je to společenství. Někteří jsou tady na konci své cesty, jiní teprve začínají. Společně neseme zodpovědnost. Voda, krmení, čištění, péče. Ráno, poledne, večer. Každý den.' },
        { type: 'p', text: 'K tomu se přidává starost o samotnou louku — sečení, vysazování, péče o stromy, ploty, dřevo. Není to romantika z Instagramu. Je to ohromná fyzická a soustavná práce.' },
        { type: 'h2', text: 'Sociální sítě a AI mezi stájemi' },
        { type: 'p', text: 'A přesto — nebo právě proto — řeším taky AI a digitální nástroje. Sociální sítě, web, projekty jako Nech mě růst, Impactly, ČSOP. Často mezi vyhazováním hnoje a šálkem čaje.' },
        { type: 'p', text: 'Dlouho mi přišlo, že mám dva životy. Jeden se zaprášenými botami a druhý před monitorem. Snažím se je uzavřít do jednoho dechu — louka i klávesnice ze stejné lásky.' },
        { type: 'h2', text: 'AI nám konečně uvolňuje ruce' },
        { type: 'callout', text: 'Konečně se dostáváme do fáze, kdy nám AI může opravdu pomoct. Nemluvím o náhradě člověka. Mluvím o tom, že mi to po deseti letech vrací několik hodin denně.' },
        { type: 'p', text: 'AI mi pomáhá psát příspěvky, plánovat, udržovat web v běhu, odpovídat na zprávy, ladit detaily. Ne místo mě — vedle mě, na pozadí. A já zatím můžu jít obejít koně.' },
        { type: 'p', text: 'Tohle je pro mě skutečný smysl technologií: ne připoutat člověka k obrazovce, ale uvolnit mu ruce pro to, co opravdu žije. Aby se mohl vrátit do trávy.' },
        { type: 'quote', text: '— Tony' },
      ],
      en: [
        { type: 'p', text: 'When I wake in the morning, the first thing I do is walk the stables. More than a hundred souls — donkey, sheep, mouflon, hens, geese, dogs, cats, cows. Each with its own name, its own temperament, its own daily need.' },
        { type: 'h2', text: 'All day: feed, water, soil' },
        { type: 'p', text: 'We live in a landscape we have inherited. Not a zoo, not a farm — a community. Some are at the end of their journey, others just beginning. Together we carry the responsibility. Water, feed, cleaning, care. Morning, noon, evening. Every day.' },
        { type: 'p', text: 'On top of that comes the meadow itself — mowing, planting, caring for trees, fences, wood. It is not Instagram romance. It is enormous, continuous physical work.' },
        { type: 'h2', text: 'Social media and AI between the stables' },
        { type: 'p', text: 'And yet — or precisely because of it — I also work with AI and digital tools. Social media, the website, projects like Nech mě růst, Impactly, ČSOP. Often between shovelling manure and a cup of tea.' },
        { type: 'p', text: 'For a long time it felt like I had two lives. One with dusty boots, one in front of a monitor. I am trying to close them into one breath — the meadow and the keyboard from the same love.' },
        { type: 'h2', text: 'AI is finally freeing our hands' },
        { type: 'callout', text: 'We are finally entering a phase where AI can truly help. I am not talking about replacing a human. I am talking about it returning to me, after ten years, several hours a day.' },
        { type: 'p', text: 'AI helps me write posts, plan, keep the site running, answer messages, fine-tune details. Not instead of me — beside me, in the background. And meanwhile I can go and check on the horses.' },
        { type: 'p', text: 'This, to me, is the real meaning of technology: not to chain a person to a screen, but to free their hands for what truly lives. So they can return to the grass.' },
        { type: 'quote', text: '— Tony' },
      ],
      ru: [
        { type: 'p', text: 'Когда я утром встаю, первое, что я делаю, — обхожу конюшни. Более ста душ: лошади, овцы, козы, куры, гуси, собаки, кошки, коровы. У каждого своё имя, свой характер, своя ежедневная нужда.' },
        { type: 'h2', text: 'Весь день: корм, вода, земля' },
        { type: 'p', text: 'Мы живём в ландшафте, который нам достался. Это не зоопарк и не ферма — это сообщество. Кто-то в конце своего пути, кто-то только начал. Вместе мы несём ответственность. Вода, корм, уборка, забота. Утро, полдень, вечер. Каждый день.' },
        { type: 'p', text: 'Ко всему этому — сам луг: косьба, посадки, уход за деревьями, заборами, дровами. Это не романтика из Instagram. Это огромная и постоянная физическая работа.' },
        { type: 'h2', text: 'Соцсети и ИИ между конюшнями' },
        { type: 'p', text: 'И всё же — или именно поэтому — я ещё занимаюсь ИИ и цифровыми инструментами. Соцсети, сайт, проекты вроде Nech mě růst, Impactly, ČSOP. Часто между уборкой навоза и чашкой чая.' },
        { type: 'p', text: 'Долго мне казалось, что у меня две жизни. Одна — в пыльных ботинках, другая — перед монитором. Я пытаюсь свести их в один вдох: луг и клавиатура из одной любви.' },
        { type: 'h2', text: 'ИИ наконец-то освобождает руки' },
        { type: 'callout', text: 'Мы наконец входим в фазу, где ИИ реально помогает. Я не говорю о замене человека. Я говорю о том, что он возвращает мне после десяти лет несколько часов в день.' },
        { type: 'p', text: 'ИИ помогает мне писать посты, планировать, поддерживать сайт, отвечать на сообщения, шлифовать детали. Не вместо меня — рядом, на фоне. А я тем временем иду проведать лошадей.' },
        { type: 'p', text: 'Для меня в этом и есть смысл технологий: не приковать человека к экрану, а освободить руки для того, что действительно живёт. Чтобы он мог вернуться в траву.' },
        { type: 'quote', text: '— Tony' },
      ],
    },
  },
];
