// ---------------------------------------------------------------------------
// BLOG — posts and translations
// All content for /blog and /blog/:slug lives here.
// Edit titles, excerpts and body blocks freely. Body blocks support:
//   { type: 'p', text: '...' }            — paragraph
//   { type: 'h2', text: '...' }           — section heading
//   { type: 'list', items: ['..', '..'] } — bullet list
//   { type: 'callout', text: '...' }      — highlighted box (gold)
//   { type: 'quote', text: '...' }        — italic quote / signature
//   { type: 'cta', text: '...', href: '...' } — gold CTA button
// ---------------------------------------------------------------------------

// ⚠️ Replace this with your real Emergent affiliate link
export const EMERGENT_AFFILIATE = 'https://app.emergent.sh/register?ref=tony375739';

export const BLOG_PAGE = {
  cs: {
    kicker: 'Zápisky',
    title: 'Co píšu,\nco žiju.',
    subtitle:
      'Pomalé poznámky z místa, kde se kořeny potkávají s kódem. Texty o nástrojích, o životě se zvířaty, o spojení toho zdánlivě nespojitelného.',
    readTime: 'min čtení',
    back: '← Zpět na úvod',
    backToList: '← Zpět na všechny zápisky',
    publishedOn: 'Publikováno',
    share: 'Sdílet',
  },
  en: {
    kicker: 'Notes',
    title: 'What I write,\nwhat I live.',
    subtitle:
      'Slow notes from a place where roots meet code. On tools, life with animals, and joining the seemingly unjoinable.',
    readTime: 'min read',
    back: '← Back home',
    backToList: '← Back to all notes',
    publishedOn: 'Published',
    share: 'Share',
  },
  ru: {
    kicker: 'Заметки',
    title: 'Что пишу,\nчем живу.',
    subtitle:
      'Медленные заметки оттуда, где корни встречают код. О инструментах, о жизни с животными и о соединении того, что кажется несоединимым.',
    readTime: 'мин чтения',
    back: '← На главную',
    backToList: '← Ко всем заметкам',
    publishedOn: 'Опубликовано',
    share: 'Поделиться',
  },
};

export const POSTS = [
  {
    id: 'claude-ekosystem',
    slug: 'claude-ekosystem-vice-nez-chatbot',
    date: '2026-05-13',
    accent: '#7c6fb0',
    readTime: 8,
    category: { cs: 'Nástroje', en: 'Tooling', ru: 'Инструменты' },
    title: {
      cs: 'Claude ekosystém: více než chatbot',
      en: 'The Claude ecosystem: more than a chatbot',
      ru: 'Экосистема Claude: больше чем чатбот',
    },
    excerpt: {
      cs: 'Claude není jedna aplikace — je to ekosystém. Webová verze, desktopová aplikace, terminálový nástroj pro vývojáře, propojitelný s čímkoli. Tady je přehled toho, jak to celé funguje — a proč mi to vrací hodiny.',
      en: 'Claude is not one application — it is an ecosystem. A web app, a desktop app, a terminal tool for developers, connectable to almost anything. Here is how it all works — and why it gives me back hours.',
      ru: 'Claude — это не одно приложение, это экосистема. Веб-версия, десктопное приложение, терминальный инструмент для разработчиков, интегрируемый с чем угодно. Вот как всё это работает — и почему это возвращает мне часы.',
    },
    body: {
      cs: [
        { type: 'p', text: 'Denně pracuji s Claudem. Na texty, na kód, na plánování, na přemýšlení nahlas. Někdy ho použiji čtyřicetkrát za den, jindy jednou — ale skoro vždy. A v posledním půl roce se z jednoduchého chatbotu vyvinulo celé prostředí, které funguje jinak, než jsem čekal.' },
        { type: 'h2', text: 'Co tvoří Claude ekosystém?' },
        { type: 'p', text: 'Claude není jedna aplikace. Je to ekosystém — webová aplikace, desktopová aplikace, vývojářský CLI nástroj, API. Každá část funguje jinak, každá se hodí na něco jiného. Zajímavé je, že je lze propojit — a právě tam se začíná dít něco skutečně užitečného.' },
        { type: 'h2', text: 'Claude.ai — kde to začíná' },
        { type: 'p', text: 'Webová verze na claude.ai je vstupní brána pro většinu lidí. Funguje v prohlížeči, nevyžaduje instalaci, zvládá texty, analýzu dokumentů, tvorbu kódu i kreativní psaní. V placené verzi máte přístup k nejnovějším modelům a obrovskému kontextovému oknu — až 200 000 tokenů, tedy přibližně 500 stránek A4 najednou.' },
        { type: 'list', items: [
          'Nahrajte celý PDF nebo dokument a ptejte se na konkrétní části — Claude přečte celou smlouvu nebo výzkumnou zprávu',
          'Použijte Projects — Claude si bude pamatovat kontext vašeho projektu přes více konverzací, ne jen v jednom okně',
          'Dejte Claudovi roli: "Jsi zkušený copywriter zaměřený na sustainability..." — výrazně to mění tón a hloubku odpovědí',
          'Pište po krocích, ne v jedné masivní zprávě — Claude reaguje lépe na jasné, ohraničené instrukce',
          'Nebojte se říct "to není co jsem chtěl, zkus jinak" — Claude se neurazí a nenechat ho opravit chybu je plýtvání',
        ]},
        { type: 'callout', text: 'Claude Sonnet 4.5 zvládne analyzovat dokument o délce celé knihy najednou. 200 000 tokenů = přibližně 150 000 slov. V praxi: nahrajte celou kódovou základnu, smlouvu nebo výzkumnou zprávu — a ptejte se.' },
        { type: 'h2', text: 'Claude Desktop — AI přímo ve vašem počítači' },
        { type: 'p', text: 'Claude Desktop je desktopová aplikace pro Mac a Windows. Sama o sobě vypadá podobně jako webová verze — ale skrývá jednu zásadní schopnost: podporu MCP, neboli Model Context Protocol.' },
        { type: 'p', text: 'MCP je otevřený standard, který umožňuje Claudovi připojit se k externím nástrojům a datům. V praxi: Claude může přistupovat k vašim souborům, spouštět příkazy, číst databáze, komunikovat s Notionem, Obsidianem, GitHubem nebo Jirou — vším, co si nainstalujete jako MCP server.' },
        { type: 'list', items: [
          'Filesystem MCP server — Claude pak může číst a upravovat soubory ve vámi určených složkách na disku',
          'GitHub MCP — Claude prochází vaše repozitáře, komentáře a pull requesty přímo z konverzace',
          'Brave Search MCP — Claude dostane přístup k webu v reálném čase, ne jen ke svým trénovacím datům',
          'Obsidian nebo Notion MCP — Claude se stane asistentem zapojeným přímo do vašich poznámek',
          'MCP servery jsou open source a přibývají rychle — hledejte na mcp.so',
        ]},
        { type: 'callout', text: 'MCP (Model Context Protocol) je pravděpodobně největší tichá revoluce v AI nástrojích letošního roku. Není to funkce — je to architektura. Díky ní Claude přestává být chatbot a stává se skutečným digitálním asistentem, který vidí váš systém.' },
        { type: 'h2', text: 'Claude Code — programování jako dialog' },
        { type: 'p', text: 'Claude Code je CLI nástroj — spustíte ho v terminálu ve složce vašeho projektu a začnete psát. Je to nejbližší věc k tomu, mít zkušeného vývojáře sedícího vedle vás. Nečte jen kód — rozumí celé kódové základně, hledá příčiny chyb, navrhuje architekturu, píše testy, commituje změny. Tenhle text vznikl ve složce webu, který stavím — a Claude Code pracoval vedle mě celou dobu.' },
        { type: 'list', items: [
          'Spusťte ho příkazem claude v terminálu — při prvním spuštění sám prozkoumá projekt',
          'Použijte /plan před větší změnou — Claude nejprve navrhne postup a čeká na váš souhlas',
          'Pracuje s git automaticky — čte diff, loguje historii, commituje se smysluplnými zprávami',
          'Řekněte mu "spusť testy a oprav co selže" — udělá to celé sám, krok za krokem',
          'Přidejte CLAUDE.md do kořene projektu — soubor s instrukcemi, který Claude čte při každém spuštění',
          'Používejte /compact v dlouhých sezeních — Claude shrne kontext a pokračuje efektivněji',
        ]},
        { type: 'callout', text: 'Claude Code má přístup k internetu, terminálu, souborům a git. Dokáže sám spustit server, zkontrolovat výsledek v prohlížeči a opravit chybu — bez toho, abyste museli přepínat okna.' },
        { type: 'h2', text: 'Projects — Claude, který vás zná' },
        { type: 'p', text: 'Projects jsou jednou z nejpodceňovanějších funkcí celého ekosystému. Dostupné ve webové aplikaci i v Desktopu — fungují jako trvalý kontext. Claude si pamatuje, co jste řekli, jaká jsou vaše pravidla, co je projekt a co jste již vyřešili. Nepotřebujete to říkat znovu.' },
        { type: 'list', items: [
          'Vytvořte oddělené projekty pro různé okruhy: práce, osobní projekty, tvorba obsahu',
          'Nastavte projektové instrukce (System Prompt) — Claude pak automaticky ví, kdo jste a jak má reagovat',
          'Přidejte do projektu klíčové dokumenty — Claude je čte jako základ každé nové konverzace',
        ]},
        { type: 'h2', text: 'Zajímavosti, které možná nevíte' },
        { type: 'list', items: [
          'Claude byl trénován metodou Constitutional AI — místo lidských hodnotitelů pro každý výstup ho Anthropic učí souborem principů, které si sám aplikuje',
          'Claude 4.x modely mají "extended thinking" — Claude může přemýšlet déle než odpovídá, výsledky jsou viditelně hlubší, a celý myšlenkový proces si můžete zobrazit',
          'Claude Code vznikl z interního nástroje, který vývojáři v Anthropic používali sami pro sebe',
          'Anthropic zveřejnila "Character Spec" — veřejný dokument popisující, co Claude je a jak přemýšlí. Neobvyklé čtení pro každého, kdo s AI pracuje pravidelně',
          'Claude explicitně odmítá tzv. "epistemic cowardice" — vyhýbavé odpovědi jen proto, aby vás nerozrušil. Anthropic to trénuje ven záměrně',
          'Claude nemá přístup k internetu ve výchozím stavu — vše co víte pochází z tréninku, ne z aktuálního webu. MCP to mění.',
        ]},
        { type: 'h2', text: 'Jak na to v praxi' },
        { type: 'p', text: 'Můj vlastní setup: Claude.ai na texty a přemýšlení. Claude Desktop s MCP serverem pro soubory a Obsidian. Claude Code na vývoj — denně, v každém projektu. Projects pro každý větší kontext, ke kterému se pravidelně vracím.' },
        { type: 'p', text: 'Není to složité. Je to prostě víc míst, kde stejně dobrý spolupracovník umí dělat různé věci. A to mi, upřímně, vrací hodiny. Hodiny, které jdu raději strávit na louce.' },
        { type: 'quote', text: 'Nejlepší nástroj je ten, který přestanete vnímat jako nástroj — a začnete vnímat jako kolegu.' },
      ],
      en: [
        { type: 'p', text: 'I use Claude daily. For writing, for code, for thinking through problems out loud. Sometimes forty times a day, sometimes once — but almost always. Over the past six months, what started as a simple chatbot has grown into an entire environment that works differently than I expected.' },
        { type: 'h2', text: 'What makes up the Claude ecosystem?' },
        { type: 'p', text: 'Claude is not one application. It is an ecosystem — a web app, a desktop app, a developer CLI tool, an API. Each part works differently, each suits a different need. What matters is that they can be connected — and that is where things get genuinely useful.' },
        { type: 'h2', text: 'Claude.ai — where it starts' },
        { type: 'p', text: 'The web app at claude.ai is the entry point for most people. It runs in a browser, needs no installation, handles writing, document analysis, code, and creative work. On the paid plan you get access to the latest models and a vast context window — up to 200,000 tokens, roughly 500 A4 pages at once.' },
        { type: 'list', items: [
          'Upload a full PDF or document and ask questions about specific sections — Claude will read an entire contract or research report',
          'Use Projects — Claude remembers your project context across multiple conversations, not just within one window',
          'Give Claude a role upfront: "You are an experienced copywriter focused on sustainability..." — it changes the tone and depth noticeably',
          'Write step by step, not in one massive message — Claude responds better to clear, bounded instructions',
          'Do not hesitate to say "that is not what I wanted, try again" — Claude does not take offence, and not letting it correct a mistake is wasted potential',
        ]},
        { type: 'callout', text: 'Claude Sonnet 4.5 can analyse a document the length of an entire book in one go. 200,000 tokens = roughly 150,000 words. In practice: upload an entire codebase, contract, or research report — and start asking.' },
        { type: 'h2', text: 'Claude Desktop — AI on your machine' },
        { type: 'p', text: 'Claude Desktop is a desktop app for Mac and Windows. On the surface it looks similar to the web version — but it hides one crucial capability: MCP support, or Model Context Protocol.' },
        { type: 'p', text: 'MCP is an open standard that lets Claude connect to external tools and data. In practice: Claude can access your files, run commands, read databases, and communicate with Notion, Obsidian, GitHub, or Jira — anything you install as an MCP server.' },
        { type: 'list', items: [
          'Filesystem MCP server — Claude can read and edit files in folders you specify on your disk',
          'GitHub MCP — Claude browses your repositories, comments, and pull requests directly from the conversation',
          'Brave Search MCP — Claude gets real-time access to the web, not just its training data',
          'Obsidian or Notion MCP — Claude becomes an assistant embedded directly inside your notes',
          'MCP servers are open source and growing fast — browse mcp.so',
        ]},
        { type: 'callout', text: 'MCP (Model Context Protocol) is probably the biggest quiet revolution in AI tooling this year. It is not a feature — it is an architecture. Through it, Claude stops being a chatbot and becomes a real digital assistant that sees your system.' },
        { type: 'h2', text: 'Claude Code — programming as dialogue' },
        { type: 'p', text: 'Claude Code is a CLI tool — you run it in your terminal inside a project folder and start writing. It is the closest thing to having an experienced developer sitting beside you. It does not just read code — it understands the entire codebase, tracks down the causes of bugs, proposes architecture, writes tests, and commits changes. This article was written in the folder of the site I am building — and Claude Code worked alongside me throughout.' },
        { type: 'list', items: [
          'Start it with the claude command in your terminal — on first run it explores the project on its own',
          'Use /plan before a bigger change — Claude proposes a plan first and waits for your approval',
          'It works with git automatically — reads diffs, checks history, commits with meaningful messages',
          'Tell it "run the tests and fix what fails" — it will do the whole thing, step by step',
          'Add CLAUDE.md to the root of your project — a set of instructions Claude reads on every launch',
          'Use /compact in long sessions — Claude summarises the context and continues more efficiently',
        ]},
        { type: 'callout', text: 'Claude Code has access to the internet, terminal, files, and git. It can start a server, check the result in a browser, and fix the error — without you switching windows.' },
        { type: 'h2', text: 'Projects — Claude that knows you' },
        { type: 'p', text: 'Projects are one of the most underrated features of the whole ecosystem. Available in both the web app and Desktop, they work as persistent context — Claude remembers what you said, your preferred rules, what the project is, and what you have already solved. You do not need to say it again.' },
        { type: 'list', items: [
          'Create separate projects for different areas: work, personal projects, content creation',
          'Set project instructions (System Prompt) — Claude then automatically knows who you are and how to respond',
          'Add key documents to the project — Claude reads them as a foundation for every new conversation',
        ]},
        { type: 'h2', text: 'Things you may not know' },
        { type: 'list', items: [
          'Claude was trained using Constitutional AI — instead of human raters for every output, Anthropic teaches it a set of principles it applies to itself',
          'Claude 4.x models have extended thinking — Claude can deliberate longer before answering, the results are visibly deeper, and you can see the entire reasoning process',
          'Claude Code grew from an internal tool that Anthropic developers used for themselves',
          'Anthropic published a "Character Spec" — a public document describing what Claude is and how it thinks. Unusual reading for anyone who works with AI regularly',
          'Claude explicitly rejects "epistemic cowardice" — vague answers given just to avoid upsetting you. Anthropic trains against this deliberately',
          'Claude has no internet access by default — everything it knows comes from training, not the current web. MCP changes that.',
        ]},
        { type: 'h2', text: 'How I use it in practice' },
        { type: 'p', text: 'My own setup: Claude.ai for writing and thinking. Claude Desktop with an MCP server for files and Obsidian. Claude Code for development — daily, in every project. Projects for every larger context I return to regularly.' },
        { type: 'p', text: 'It is not complicated. It is just more places where the same good collaborator can do different things. And that, honestly, gives me back hours. Hours I would rather spend on the meadow.' },
        { type: 'quote', text: 'The best tool is the one you stop perceiving as a tool — and start experiencing as a colleague.' },
      ],
      ru: [
        { type: 'p', text: 'Я использую Claude каждый день. Для текстов, кода, планирования, для того чтобы думать вслух. Иногда сорок раз за день, иногда один — но почти всегда. За последние полгода то, что начиналось как простой чатбот, превратилось в целую среду, которая работает не так, как я ожидал.' },
        { type: 'h2', text: 'Из чего состоит экосистема Claude?' },
        { type: 'p', text: 'Claude — это не одно приложение. Это экосистема: веб-приложение, десктопное приложение, CLI-инструмент для разработчиков, API. Каждая часть работает по-своему, каждая подходит для своего. Важно то, что они соединяются — и вот тут начинается что-то действительно полезное.' },
        { type: 'h2', text: 'Claude.ai — с чего начинается' },
        { type: 'p', text: 'Веб-версия на claude.ai — точка входа для большинства. Работает в браузере, не требует установки, справляется с текстами, анализом документов, кодом и творческим письмом. На платном тарифе есть доступ к последним моделям и огромному контекстному окну — до 200 000 токенов, то есть примерно 500 страниц А4 за раз.' },
        { type: 'list', items: [
          'Загрузите целый PDF или документ и задавайте вопросы по конкретным частям — Claude прочтёт весь договор или исследовательский отчёт',
          'Используйте Projects — Claude запомнит контекст вашего проекта в разных разговорах, а не только в одном окне',
          'Задайте Claude роль в начале: "Ты опытный копирайтер в области экологии..." — это заметно меняет тон и глубину ответов',
          'Пишите пошагово, а не в одном огромном сообщении — Claude лучше реагирует на чёткие, ограниченные инструкции',
          'Не стесняйтесь говорить "это не то, что я хотел, попробуй иначе" — Claude не обидится, а не дать ему исправить ошибку — значит терять потенциал',
        ]},
        { type: 'callout', text: 'Claude Sonnet 4.5 может проанализировать документ длиной с целую книгу за один раз. 200 000 токенов — это примерно 150 000 слов. На практике: загрузите целую кодовую базу, договор или исследование — и начните задавать вопросы.' },
        { type: 'h2', text: 'Claude Desktop — ИИ прямо на вашем компьютере' },
        { type: 'p', text: 'Claude Desktop — десктопное приложение для Mac и Windows. Внешне оно похоже на веб-версию, но скрывает одну ключевую возможность: поддержку MCP, или Model Context Protocol.' },
        { type: 'p', text: 'MCP — открытый стандарт, позволяющий Claude подключаться к внешним инструментам и данным. На практике: Claude может работать с вашими файлами, запускать команды, читать базы данных, общаться с Notion, Obsidian, GitHub или Jira — с чем угодно, что вы установили как MCP-сервер.' },
        { type: 'list', items: [
          'Filesystem MCP сервер — Claude читает и редактирует файлы в папках, которые вы ему разрешили',
          'GitHub MCP — Claude просматривает ваши репозитории, комментарии и пул-реквесты прямо из диалога',
          'Brave Search MCP — Claude получает доступ к актуальному вебу, а не только к обучающим данным',
          'Obsidian или Notion MCP — Claude становится ассистентом, встроенным прямо в ваши заметки',
          'MCP-серверы открытые и их становится всё больше — смотрите на mcp.so',
        ]},
        { type: 'callout', text: 'MCP (Model Context Protocol) — вероятно, самая тихая революция в AI-инструментах этого года. Это не функция — это архитектура. Благодаря ей Claude перестаёт быть чатботом и становится настоящим цифровым ассистентом, который видит вашу систему.' },
        { type: 'h2', text: 'Claude Code — программирование как диалог' },
        { type: 'p', text: 'Claude Code — CLI-инструмент. Вы запускаете его в терминале в папке проекта и начинаете писать. Это ближайшее, что есть, к тому чтобы опытный разработчик сидел рядом с вами. Он не просто читает код — он понимает всю кодовую базу, находит причины ошибок, предлагает архитектуру, пишет тесты, делает коммиты. Эта статья написана в папке сайта, который я строю — и Claude Code работал рядом всё это время.' },
        { type: 'list', items: [
          'Запустите командой claude в терминале — при первом запуске он сам изучит проект',
          'Используйте /plan перед большим изменением — Claude сначала предложит план и подождёт вашего одобрения',
          'Работает с git автоматически — читает диффы, проверяет историю, делает коммиты с понятными сообщениями',
          'Скажите ему "запусти тесты и исправь что не прошло" — он сделает всё пошагово сам',
          'Добавьте CLAUDE.md в корень проекта — файл с инструкциями, который Claude читает при каждом запуске',
          'Используйте /compact в длинных сессиях — Claude сожмёт контекст и продолжит эффективнее',
        ]},
        { type: 'callout', text: 'Claude Code имеет доступ к интернету, терминалу, файлам и git. Он может запустить сервер, проверить результат в браузере и исправить ошибку — пока вы не переключали ни одного окна.' },
        { type: 'h2', text: 'Projects — Claude, который вас знает' },
        { type: 'p', text: 'Projects — одна из самых недооценённых функций всей экосистемы. Доступна и в веб-версии, и в Desktop. Работает как постоянный контекст: Claude помнит, что вы говорили, какие у вас правила, что это за проект и что вы уже решили. Повторять не нужно.' },
        { type: 'list', items: [
          'Создайте отдельные проекты для разных направлений: работа, личные проекты, контент',
          'Настройте инструкции проекта (System Prompt) — Claude будет автоматически знать, кто вы и как реагировать',
          'Добавьте ключевые документы в проект — Claude читает их как основу каждого нового разговора',
        ]},
        { type: 'h2', text: 'Факты, которые вы могли не знать' },
        { type: 'list', items: [
          'Claude обучался методом Constitutional AI — вместо людей-оценщиков для каждого ответа Anthropic обучает его набору принципов, которые он применяет сам к себе',
          'Модели Claude 4.x имеют extended thinking — Claude может думать дольше перед ответом, результаты заметно глубже, и весь ход мысли можно увидеть',
          'Claude Code вырос из внутреннего инструмента, который разработчики Anthropic использовали сами',
          'Anthropic опубликовала "Character Spec" — публичный документ, описывающий что такое Claude и как он мыслит. Необычное чтение для тех, кто регулярно работает с ИИ',
          'Claude явно отказывается от "epistemic cowardice" — уклончивых ответов, лишь бы вас не расстраивать. Anthropic намеренно это убирает при обучении',
          'У Claude нет доступа к интернету по умолчанию — всё, что он знает, из тренировочных данных, а не с актуального веба. MCP это меняет.',
        ]},
        { type: 'h2', text: 'Как это использую я' },
        { type: 'p', text: 'Мой личный стек: Claude.ai для текстов и мышления. Claude Desktop с MCP-сервером для файлов и Obsidian. Claude Code для разработки — каждый день, в каждом проекте. Projects для любого крупного контекста, к которому возвращаюсь регулярно.' },
        { type: 'p', text: 'Это не сложно. Просто больше мест, где один и тот же хороший коллега умеет делать разные вещи. И это честно возвращает мне часы. Часы, которые я лучше проведу на лугу.' },
        { type: 'quote', text: 'Лучший инструмент — тот, который перестаёшь воспринимать как инструмент и начинаешь воспринимать как коллегу.' },
      ],
    },
  },
{
  id: 'ochrana-prirody-2026',
  slug: 'ochrana-prirody-2026-financni-krize',
  date: '2026-05-06',
  accent: '#4a8c5c',
  readTime: 8,
  category: { cs: 'Příroda', en: 'Nature', ru: 'Природа' },
  title: {
    cs: 'Ochrana přírody v roce 2026: kdo to vlastně platí?',
    en: 'Nature conservation in 2026: who is actually paying for it?',
    ru: 'Охрана природы в 2026 году: кто за это платит?',
  },
  excerpt: {
    cs: 'Stát škrtá rozpočty národních parků až o 41 %. Ochránci sahají do vlastní kapsy. A Evropa mezitím požaduje víc. Tohle je obraz české ochrany přírody v roce 2026.',
    en: 'The state cuts national park budgets by up to 41%. Conservationists reach into their own pockets. And Europe demands more. This is the picture of Czech nature conservation in 2026.',
    ru: 'Государство урезает бюджеты национальных парков на 41%. Защитники природы платят из своего кармана. А Европа тем временем требует большего. Таков облик охраны природы в Чехии в 2026 году.',
  },
  body: {
    cs: [
      { type: 'p', text: 'Na jaře, kdy se louka probouzí, je práce vidět přímo pod rukama. Tráva roste, zvířata se pasou, voda se vrací do půdy. Tohle je ochrana přírody v té nejkonkrétnější podobě — fyzická, každodenní, tichá. Bez tiskových konferencí, bez dotačních žádostí, bez ministrů.' },
      { type: 'p', text: 'Jenže ta širší, institucionální ochrana přírody — ta, která chrání celé krajiny, vede záchranné programy, mapuje druhy a udržuje národní parky — ta se v roce 2026 nachází v situaci, která by za normálních okolností vyvolala bouřlivou veřejnou debatu. Nestala se tak velkou. A to je možná největší problém.' },
      { type: 'h2', text: 'Čísla, která se nemají ztratit v tabulkách' },
      { type: 'p', text: 'Národní park Šumava dostane v roce 2026 od státu o 40,9 % méně peněz než loni. Krkonošský národní park přijde o 23,6 %. Správy parků oznámily, že budou muset sáhnout do rezervních fondů — těch, které byly původně určeny pro kůrovcové a větrné kalamity, tedy pro skutečné nouzové situace. Teď slouží k pokrytí běžného provozu.' },
      { type: 'callout', text: 'NP Šumava: příspěvek 2025 → 182 milionů Kč. Návrh pro rok 2026 → 107,6 milionů Kč. Pokles o 41 %.' },
      { type: 'p', text: 'To není drobná korekce. To je strukturální změna v tom, jak stát přistupuje ke krajině, kterou sám vyhlásil za chráněnou. A zároveň — a to je důležité říct nahlas — v témže roce Evropská unie po České republice vyžaduje předložení Národního plánu obnovy přírody. Do 1. září 2026. Komplexní dokument, který má naplánovat obnovu poškozených ekosystémů na příštích dvacet pět let.' },
      { type: 'p', text: 'Stát tedy jednou rukou píše plány na záchranu krajiny. Druhou rukou škrtá prostředky těm, kdo ji mají chránit dnes.' },
      { type: 'h2', text: 'Ochránci, kteří platí ze své kapsy' },
      { type: 'p', text: 'Za čísly v tabulkách jsou konkrétní lidé. Ochránci přírody, kteří jedou na terénní průzkum vlastním autem, protože na benzín už nejsou prostředky. Dobrovolníci, kteří si sami platí vybavení na monitoring. Organizace, které pořádají sbírky, aby vůbec mohly dělat to, co stát formálně označuje za svou prioritu.' },
      { type: 'p', text: 'Český svaz ochránců přírody — síť, bez které by se česká krajina v mnoha lokalitách dávno vzdala — funguje z části právě na tomto principu. Projekt Sedmihorské mokřady v Českém ráji, kde letos podruhé za sebou úspěšně vyhnízdili jeřábi popelaví, se financuje i přes kampaň „Pošli kapku" — veřejnou sbírku na výkup dalších pozemků. Stát takovou lokalitu chrání na papíře. Kdo ji chrání v terénu, si na to vybírá peníze od lidí.' },
      { type: 'p', text: 'Tohle není výjimka. Tohle se stává modelem.' },
      { type: 'h2', text: 'Ministr, který radí parkům, ať si vydělají samy' },
      { type: 'p', text: 'Ministr životního prostředí Igor Červený z hnutí Motoristé otevřeně vyzývá národní parky, aby začaly více využívat svůj ekonomický potenciál. V praxi to znamená debatu o zpoplatnění vstupu do části chráněných území nebo parkování u vstupních bodů. Tedy — místa, která jsou chráněna právě proto, aby nebyla primárně ekonomicky využívána, mají začít fungovat jako turistické atrakce s kasičkou u brány.' },
      { type: 'p', text: 'Chápu logiku úspor. Chápu, že státní rozpočet má své limity. Ale je v tom hluboký paradox: chráněná území vznikla jako odpověď na nadměrnou ekonomizaci krajiny. Nyní jsou vyzývána, aby se ekonomizovala, aby přežila.' },
      { type: 'h2', text: 'Zatímco Evropa tlačí na plyn' },
      { type: 'p', text: 'Na evropské úrovni se mezitím děje opak. Nařízení o obnově přírody z roku 2024 je jedním z nejambicióznějších legislativních kroků v historii ochrany biodiverzity. Česká republika má závazky — obnovit poškozené ekosystémy, zastavit úbytek druhů, zvýšit konektivitu krajiny. Součástí je i cíl striktně chránit 10 % území EU, kde probíhají přirozené procesy bez lidských zásahů.' },
      { type: 'p', text: 'Tyto závazky nikdo nezrušil. Nekrátí se. Jsou platné a vynutitelné. Jen se krátí prostředky na jejich naplňování. Výsledek je předvídatelný: ambiciózní strategie bez reálného krytí. Dokumenty, které opisují evropské cíle, a správy parků, které nevědí, jestli udrží provoz.' },
      { type: 'h2', text: 'Co zůstává' },
      { type: 'p', text: 'Přesto se věci dějí. Bylo vypuštěno 115 sysů obecných na pět lokalit. Kočka divoká se vrátila do Lužických hor — poprvé po desetiletích potvrzené rozmnožování. Projekt managementu Sedmihorských mokřadů běží. ČSOP vyhlásil Rok hořců a lokální organizace po celé zemi pečují o louky, mokřady a remízky, o které by se jinak nikdo nestaral.' },
      { type: 'p', text: 'Tohle přežívá. Ale přežívá navzdory systému, ne díky němu. Přežívá z vůle konkrétních lidí, kteří to dělají, i když na to nemají zaplaceno. Kteří jedou v sobotu ráno přesouvat čolky přes cestu, protože kdyby nejeli, nikdo jiný nepojede.' },
      { type: 'h2', text: 'Sbírky jako politický symptom' },
      { type: 'p', text: 'Když si musíte pořádat sbírku na záchranu mokřadu, který stát chrání zákonem, není to jen finanční problém. Je to signál o hodnotách. O tom, co považujeme za samozřejmé a co za nadstandard. Ochrana přírody se v roce 2026 posouvá do kategorie charitativní činnosti — něco, co je hezké, když na to zbyde.' },
      { type: 'p', text: 'Přitom jde o věci zcela konkrétní. O vodu v krajině, která zadrží přívalový déšť a zpomalí sucho. O opylovače, bez kterých se mění zemědělská produktivita. O druhy, které až vymřou, nevymřou tiše — vymřou jako součást systému, na jehož konci jsme i my.' },
      { type: 'p', text: 'Na louce to víte instinktivně. Když přestanete sekat, změní se druhová skladba. Když přestanete hlídat vodní režim, změní se půda. Příroda reaguje pomalu — ale reaguje. A její odolnost není neomezená.' },
      { type: 'h2', text: 'Co s tím' },
      { type: 'p', text: 'Nejsem politik ani ekonom. Ale vidím, co vidí každý, kdo tráví čas venku: péče o krajinu není luxus. Je to infrastruktura. Tichá, neviditelná, a přesto zásadní — stejně jako kanalizace nebo silnice. Akorát ta kanalizace nevyhnízdí jeřáby a silnice nezadrží vodu v půdě.' },
      { type: 'p', text: 'Pokud chcete podpořit lidi, kteří tuhle práci dělají navzdory škrtům — hledejte lokální organizace ČSOP ve svém regionu. Nebo přijďte na Loukádu. Přineste ruce a dobrou náladu. To se vždycky hodí.' },
      { type: 'quote', text: 'Příroda čeká. Otázka je, jestli my počkáme s ní.' },
    ],
    en: [
      { type: 'p', text: 'In spring, when the meadow wakes up, the work is visible right in your hands. Grass grows, animals graze, water returns to the soil. This is nature conservation in its most concrete form — physical, daily, quiet. Without press conferences, without grant applications, without ministers.' },
      { type: 'p', text: 'But the broader, institutional conservation — the kind that protects entire landscapes, runs rescue programmes, maps species, and maintains national parks — finds itself in 2026 in a situation that would normally provoke loud public debate. It has not. And that may be the biggest problem of all.' },
      { type: 'h2', text: 'Numbers that must not get lost in spreadsheets' },
      { type: 'p', text: 'Šumava National Park will receive 40.9% less state funding in 2026 than last year. Krkonoše National Park loses 23.6%. Park authorities have announced they will have to draw on reserve funds — the ones originally set aside for bark beetle and windstorm emergencies. Now those funds are covering basic operations.' },
      { type: 'callout', text: 'Šumava NP: contribution 2025 → 182 million CZK. Proposal for 2026 → 107.6 million CZK. A cut of 41%.' },
      { type: 'p', text: 'This is not a minor correction. It is a structural shift in how the state approaches the landscapes it has declared protected. And at the same time — and this needs to be said clearly — in the very same year, the European Union requires the Czech Republic to submit a National Plan for Nature Restoration. By 1 September 2026. A comprehensive document planning the restoration of damaged ecosystems for the next twenty-five years.' },
      { type: 'p', text: 'With one hand, the state writes plans to save the landscape. With the other, it cuts the resources of those responsible for protecting it today.' },
      { type: 'h2', text: 'Conservationists paying out of their own pockets' },
      { type: 'p', text: 'Behind the numbers in the spreadsheets are real people. Conservationists driving to field surveys in their own cars because there is no budget for fuel. Volunteers buying their own monitoring equipment. Organisations running crowdfunding campaigns just to do what the state formally calls a priority.' },
      { type: 'p', text: 'The Czech Union for Nature Conservation — a network without which large parts of the Czech landscape would have long been abandoned — operates partly on exactly this model. The Sedmihorské wetlands project in Bohemian Paradise, where grey cranes successfully nested for the second consecutive year, is funded in part through a public campaign called "Send a Drop" — a crowdfunder to buy more land. The state protects the site on paper. The people protecting it in the field are collecting money from the public to do so.' },
      { type: 'p', text: 'This is not an exception. This is becoming the model.' },
      { type: 'h2', text: 'A minister who tells parks to earn their own way' },
      { type: 'p', text: 'Environment Minister Igor Červený of the Motorists movement has openly urged national parks to make better use of their economic potential. In practice, this means discussion about charging entrance fees to parts of protected areas, or parking fees at entry points. In other words — places that are protected precisely because they were not to be primarily economically exploited are now being asked to function as tourist attractions with a collection box at the gate.' },
      { type: 'p', text: 'I understand the logic of austerity. I understand that the state budget has limits. But there is a deep paradox here: protected areas were created as a response to the over-commercialisation of the landscape. Now they are being asked to commercialise themselves in order to survive.' },
      { type: 'h2', text: 'While Europe presses the accelerator' },
      { type: 'p', text: 'At the European level, meanwhile, the opposite is happening. The Nature Restoration Regulation of 2024 is one of the most ambitious legislative steps in the history of biodiversity protection. The Czech Republic has commitments — to restore damaged ecosystems, halt species decline, increase landscape connectivity. Part of that includes a target to strictly protect 10% of EU territory where natural processes unfold without human interference.' },
      { type: 'p', text: 'These commitments have not been cancelled. They are not being cut. They are valid and enforceable. Only the resources to fulfil them are being cut. The result is predictable: ambitious strategies without real backing. Documents that copy European targets, and park authorities unsure whether they can keep operations running.' },
      { type: 'h2', text: 'What remains' },
      { type: 'p', text: 'And yet things are happening. 115 European ground squirrels were released at five sites. The wildcat returned to the Lusatian Mountains — confirmed breeding for the first time in decades. The Sedmihorské wetlands management project is running. ČSOP has declared the Year of Gentians and local organisations across the country are caring for meadows, wetlands and field groves that would otherwise go untended.' },
      { type: 'p', text: 'This survives. But it survives despite the system, not because of it. It survives through the will of specific people doing the work even when they are not paid for it. Who drive out on a Saturday morning to help frogs cross a road, because if they do not go, no one will.' },
      { type: 'h2', text: 'Fundraising as a political symptom' },
      { type: 'p', text: 'When you have to run a crowdfunding campaign to save a wetland that is legally protected by the state, that is not just a financial problem. It is a statement of values. About what we take for granted and what we treat as optional. Nature conservation in 2026 is drifting into the category of charity — something that is nice to have when there is something left over.' },
      { type: 'p', text: 'And yet the things at stake are entirely concrete. Water in the landscape that absorbs heavy rain and slows drought. Pollinators without which agricultural productivity shifts. Species that, when they go extinct, will not go quietly — they will go as part of a system whose end includes us.' },
      { type: 'p', text: 'On the meadow you feel this instinctively. Stop mowing and the species composition changes. Stop managing the water regime and the soil changes. Nature responds slowly — but it responds. And its resilience is not unlimited.' },
      { type: 'h2', text: 'What now' },
      { type: 'p', text: 'I am not a politician or an economist. But I see what anyone who spends time outdoors can see: caring for the landscape is not a luxury. It is infrastructure. Quiet, invisible, and yet fundamental — just like sewage systems or roads. Except sewage systems do not nest cranes and roads do not hold water in the soil.' },
      { type: 'p', text: 'If you want to support the people doing this work despite the cuts — find your local ČSOP organisation. Or come to a Loukáda. Bring your hands and good spirits. That is always useful.' },
      { type: 'quote', text: 'Nature waits. The question is whether we will wait with it.' },
    ],
    ru: [
      { type: 'p', text: 'Весной, когда луг просыпается, работа видна прямо в руках. Трава растёт, животные пасутся, вода возвращается в почву. Это охрана природы в самом конкретном виде — физическая, ежедневная, тихая. Без пресс-конференций, без заявок на гранты, без министров.' },
      { type: 'p', text: 'Но более широкая, институциональная охрана природы — та, что защищает целые ландшафты, ведёт программы спасения видов, картирует биоразнообразие и поддерживает национальные парки — в 2026 году оказалась в ситуации, которая в нормальных обстоятельствах вызвала бы громкую общественную дискуссию. Этого не произошло. И это, пожалуй, и есть главная проблема.' },
      { type: 'h2', text: 'Цифры, которые нельзя терять в таблицах' },
      { type: 'p', text: 'Национальный парк Шумава получит от государства в 2026 году на 40,9% меньше средств, чем в прошлом. Крконошский национальный парк лишается 23,6%. Администрации парков объявили, что будут вынуждены тратить резервные фонды — те самые, что предназначались для ликвидации последствий короедных и ветровальных катастроф. Теперь они идут на покрытие текущих расходов.' },
      { type: 'callout', text: 'НП Шумава: субсидия 2025 → 182 млн крон. Предложение на 2026 → 107,6 млн крон. Сокращение на 41%.' },
      { type: 'p', text: 'Это не небольшая корректировка. Это структурный сдвиг в том, как государство относится к ландшафтам, которые само же объявило охраняемыми. И одновременно — и это важно сказать прямо — в том же самом году Европейский союз требует от Чехии представить Национальный план восстановления природы. До 1 сентября 2026 года. Комплексный документ, планирующий восстановление повреждённых экосистем на следующие двадцать пять лет.' },
      { type: 'p', text: 'Одной рукой государство пишет планы по спасению природы. Другой — урезает средства тем, кто должен её защищать сегодня.' },
      { type: 'h2', text: 'Защитники природы, платящие из собственного кармана' },
      { type: 'p', text: 'За цифрами в таблицах стоят реальные люди. Защитники природы, которые едут на полевые работы на собственных машинах, потому что денег на бензин уже нет. Добровольцы, покупающие оборудование для мониторинга за свой счёт. Организации, проводящие краудфандинговые сборы, чтобы вообще иметь возможность делать то, что государство формально называет своим приоритетом.' },
      { type: 'p', text: 'Чешский союз охраны природы — сеть, без которой многие уголки чешского ландшафта давно были бы брошены — работает отчасти именно по такой модели. Проект болот Седмигорье в Чешском раю, где второй год подряд успешно гнездятся серые журавли, финансируется в том числе через публичную кампанию «Пошли каплю» — народный сбор средств на выкуп новых участков. Государство охраняет эту территорию на бумаге. Те, кто охраняет её в поле, собирают на это деньги у людей.' },
      { type: 'p', text: 'Это не исключение. Это становится нормой.' },
      { type: 'h2', text: 'Министр, советующий паркам зарабатывать самим' },
      { type: 'p', text: 'Министр окружающей среды Игор Червени от движения «Мотористы» открыто призывает национальные парки активнее использовать свой экономический потенциал. На практике это означает дискуссию о введении платного входа в части охраняемых территорий или платных парковок у въездных точек. То есть — места, которые охраняются именно потому, что не должны прежде всего приносить экономическую выгоду, теперь призывают работать как туристические аттракции с кассой у ворот.' },
      { type: 'p', text: 'Я понимаю логику экономии. Я понимаю, что госбюджет имеет свои пределы. Но здесь есть глубокий парадокс: охраняемые территории возникли как ответ на чрезмерную коммерциализацию природы. Теперь им предлагают коммерциализироваться самим, чтобы выжить.' },
      { type: 'h2', text: 'Пока Европа жмёт на газ' },
      { type: 'p', text: 'На европейском уровне тем временем происходит обратное. Регламент о восстановлении природы 2024 года — один из самых амбициозных законодательных шагов в истории охраны биоразнообразия. У Чехии есть обязательства — восстановить повреждённые экосистемы, остановить сокращение видов, повысить связность ландшафта. В том числе цель строгой охраны 10% территории ЕС, где протекают естественные процессы без вмешательства человека.' },
      { type: 'p', text: 'Эти обязательства никто не отменял. Они не сокращаются. Они действуют и подлежат исполнению. Сокращаются только ресурсы на их выполнение. Результат предсказуем: амбициозные стратегии без реального обеспечения. Документы, переписывающие европейские цели, и администрации парков, не уверенные, смогут ли они вообще поддерживать текущую деятельность.' },
      { type: 'h2', text: 'Что остаётся' },
      { type: 'p', text: 'И всё же кое-что происходит. На пять локаций выпущено 115 европейских сусликов. Дикая кошка вернулась в Лужицкие горы — впервые за десятилетия подтверждено размножение. Проект управления болотами Седмигорье работает. ČSOP объявил Год горечавок, и местные организации по всей стране ухаживают за лугами, болотами и полевыми зарослями, о которых иначе некому было бы позаботиться.' },
      { type: 'p', text: 'Всё это выживает. Но выживает вопреки системе, а не благодаря ей. Выживает силой воли конкретных людей, делающих эту работу даже тогда, когда им за неё не платят. Тех, кто в субботу утром едет помогать лягушкам перебраться через дорогу — потому что если они не поедут, не поедет никто.' },
  { type: 'h2', text: 'Сборы как политический симптом' },
      { type: 'p', text: 'Когда приходится устраивать краудфандинг для спасения болота, которое государство охраняет по закону, — это не просто финансовая проблема. Это высказывание о ценностях. О том, что мы считаем само собой разумеющимся, а что — необязательным. Охрана природы в 2026 году смещается в категорию благотворительности — того, чем хорошо бы заниматься, если остаётся время и деньги.' },
      { type: 'p', text: 'А на кону — вещи совершенно конкретные. Вода в ландшафте, поглощающая ливни и замедляющая засуху. Опылители, без которых меняется сельскохозяйственная продуктивность. Виды, которые, исчезая, исчезают не тихо — они исчезают как часть системы, конец которой касается и нас.' },
      { type: 'p', text: 'На лугу это чувствуешь инстинктивно. Перестань косить — изменится видовой состав. Перестань следить за водным режимом — изменится почва. Природа реагирует медленно — но реагирует. И её устойчивость небезгранична.' },
      { type: 'h2', text: 'Что с этим делать' },
      { type: 'p', text: 'Я не политик и не экономист. Но я вижу то, что видит каждый, кто проводит время на улице: забота о природе — не роскошь. Это инфраструктура. Тихая, невидимая и при этом фундаментальная — как канализация или дороги. Только канализация не гнездит журавлей, а дороги не удерживают воду в почве.' },
      { type: 'p', text: 'Если хотите поддержать людей, которые делают эту работу вопреки сокращениям — найдите местную организацию ČSOP в своём регионе. Или приезжайте на Loukáda. Привозите руки и хорошее настроение. Это всегда пригодится.' },
      { type: 'quote', text: 'Природа ждёт. Вопрос в том, будем ли мы ждать вместе с ней.' },
    ],
  },
},
{
  id: 'loukada-prijdte-na-louku',
  slug: 'loukada-prijdte-na-louku',
  date: '2026-05-02',
  accent: '#7ab648',
  readTime: 7,
  category: { cs: 'Příroda', en: 'Nature', ru: 'Природа' },
  title: {
    cs: 'Loukáda: Přijďte na louku, kde práce chutná jinak',
    en: 'Loukáda: Come to the meadow where work tastes different',
    ru: 'Loukáda: Приходите на луг, где работа ощущается иначе',
  },
  excerpt: {
    cs: 'Příští víkend otevíráme Louku pro všechny, kdo chtějí přiložit ruku k dílu. Pomazlit Yakula, pohladit krávu, popovídat si u práce. Jednoduše přijít.',
    en: 'Next weekend we open the meadow to everyone who wants to lend a hand. Pet Yakul, stroke a cow, talk while working. Simply come.',
    ru: 'В следующие выходные мы открываем луг для всех, кто хочет помочь руками. Погладить Якула, почесать корову, поговорить за работой. Просто приехать.',
  },
  body: {
    cs: [
      { type: 'p', text: 'Ráno na Louce začíná dřív, než se probudí většina lidí. Ještě před první kávou je potřeba zkontrolovat ohrady, přinést seno, nakrmit prasíky. Krávy stojí klidně ve svém rytmu, ovce komentují příchod hlasitě a bez zábran, psi se protahují ve zlatém světle. A někde mezi tím vším se motá malá, trochu nejistá, trochu zvědavá figurka — náš mufloní mláďák Yakul.' },
      { type: 'p', text: 'Tenhle rytmus je tady každý den. Bez výjimky, bez přerušení.' },
      { type: 'p', text: 'Ale jednou za čas se otevře i pro ostatní.' },
      { type: 'h2', text: 'Co je Loukáda?' },
      { type: 'p', text: 'Není to festival. Není to přednáška. Není to akce s programem a časovým harmonogramem.' },
      { type: 'p', text: 'Je to jednoduché: přijdete, vezmete vidle nebo lopatu, pomůžete tam, kde je třeba — a u toho se dá povídat. O zvířatech. O tom, co vás zajímá. O životě, o přírodě, o tom, co koho zrovna zaměstnává. Práce rukama totiž něco dělá s hlavou. Uvolňuje ji. Vytváří prostor, ve kterém se přirozeně mluví jinak než v komentářích na sociálních sítích nebo za stolem v kanceláři.' },
      { type: 'p', text: 'A pokud si při tom necháte přiběhnout k ruce mazlivou Atilku, otřít o nohu spokojenou kočku nebo přijde blíž mufloní mládě a začne zkoumat vaše boty — tím lépe.' },
      { type: 'h2', text: 'Příští víkend u nás na Louce' },
      { type: 'p', text: 'Zveme vás na Louku, kde projekt Nech mě růst každý den reálně žije — ne jen na obrazovce, ale ve fyzickém světě, ve špíně, v trávě, v péči o zvířata, která tady jsou a která potřebují pozornost a práci.' },
      { type: 'p', text: 'Přijďte pomoci. Přivezete-li sebou ještě nějaké dobroty — pro sebe, pro ostatní, případně vhodné pamlsky pro zvířata — budeme samozřejmě rádi. Ale není to podmínka. Podmínka je jen jedno: přijít s chutí být chvíli jinde, než jste zvyklí.' },
      { type: 'h2', text: 'Co vás čeká' },
      { type: 'p', text: 'Mufloní mládě Yakul. Jeden malý muflon. Maličký, roztomilý a stále ještě trochu překvapený světem, do kterého přišel. Sledovat ho je samo o sobě důvod přijet. Je v něm ta zvláštní směs plachosti a zvědavosti, která patří k mláďatům — přijde blíž, zastaví se, odskočí, vrátí se. Pokud máte trpělivost a zůstanete klidní, možná vás přijde očichat. A to je zážitek, který se těžko popisuje.' },
      { type: 'p', text: 'Krávy. Velcí, klidní tvorové s neuvěřitelnou pamětí na lidi. Jakmile vás poznají, zůstanou stát a nechají se pohladit. Jejich klid je nakažlivý. Lidé, kteří přišli na Loukádu poprvé, mi říkali, že stání vedle krávy je jedním z nejklidnějších zážitků, jaké zažili — a přitom to vůbec nečekali.' },
      { type: 'p', text: 'Ovce. Hlučné, zvídavé a překvapivě sociální. Mají svá pravidla, svou hierarchii, své oblíbené i neoblíbené. Chvíli je pozorovat ve stádě je jako číst knihu napsanou jazykem, který sice neznáte, ale nějak mu začnete rozumět.' },
      { type: 'p', text: 'Psi a kočky. Ti jsou všude. Vždy. Vracejí lásku přímo a bez podmínek.' },
      { type: 'h2', text: 'Proč to děláme?' },
      { type: 'p', text: 'Projekt Nech mě růst je v jádru jednoduchý: věříme, že kontakt s přírodou a se zvířaty dává životu jiný rozměr. Že fyzická práce má hodnotu, která se nedá plně nahradit. Že ticho Louky je vzácné a stojí za to ho chránit — a sdílet.' },
      { type: 'p', text: 'Loukáda není o vzdělávání ani o šíření žádné filozofie. Je to pracovní setkání s lidskou tváří. Přijdete, zapracujete, potkáte lidi, potkáte zvířata, sníte něco dobrého. To je celý plán.' },
      { type: 'p', text: 'A protože každý z nás žije trochu jiný život a zajímají ho jiné věci — někdo přijde z města, někdo z přírody, někdo řeší farmaření, někdo digitální svět, někdo prostě hledá pěkné odpoledne mimo obvyklé prostředí — témata rozhovorů vznikají sama. Nikdo je neurčuje předem.' },
      { type: 'h2', text: 'Louka jako jiný čas' },
      { type: 'p', text: 'Existuje něco, co se naučíte jen tehdy, když pracujete rukou vedle živého tvora.' },
      { type: 'p', text: 'Mufloní mládě se nezajímá, jestli jste produktivní. Kráva neví, jestli máte splněné úkoly. Ovce vám nedají zpětnou vazbu na váš výkon.' },
      { type: 'p', text: 'Ale reagují na vaši přítomnost. Na to, jak se pohybujete, jak mluvíte, jak dýcháte. V tom je tichá lekce, která se jinak těžko získá — naučit se být tam, kde právě jste.' },
      { type: 'p', text: 'Louka má svůj vlastní čas. A pokud se mu podřídíte, i jen na jeden den, vrátíte se domů zcela klidní.' },
      { type: 'h2', text: 'Praktické informace' },
      { type: 'p', text: 'Přijďte příští víkend. Oblečte si něco, co se může zašpinit. Vezměte sebou dobrou náladu a případně něco dobrého k jídlu nebo pití pro společnou pauzu — tohle vždycky potěší.' },
      { type: 'callout', text: 'Pokud chcete přivézt pamlsky pro zvířata, ideální volbou je OvoZel z farmy Jamboz, která sídlí nedaleko. Více na www.jamboz.cz' },
      { type: 'p', text: 'Loukáda není velká věc. Je to jedno odpoledne, možná celý den. Lidé přijdou, zapracují, popovídají, odejdou. Zvířata zůstanou — jako vždy.' },
      { type: 'p', text: 'Ale taková setkání mají váhu, která se jinak těžko nachází. Sdílená práce, fyzická přítomnost, kontakt se zvířaty, s půdou, s rytmem, který neřídíme my — to si neseme dál, i když si to v tu chvíli neuvědomujeme.' },
      { type: 'p', text: 'Projekt Nech mě růst existuje, protože věříme, že tohle má smysl. Že Louka je místo, kam se vyplatí přijít. Že mufloní mládě, které vám přijde oňuchat ruku, vám toho řekne víc než ledajaký víkendový kurz.' },
      { type: 'quote', text: 'Uvidíme se na Louce.' },
    ],
    en: [
      { type: 'p', text: 'Morning on the meadow starts before most people wake up. Before the first coffee there are fences to check, hay to carry, piglets to feed. The cows stand calm in their rhythm, the sheep announce your arrival loudly and without restraint, the dogs stretch in golden light. And somewhere in the middle of all this wanders a small, slightly uncertain, slightly curious figure — our mouflon fawn Yakul.' },
      { type: 'p', text: 'This rhythm is here every day. Without exception, without interruption.' },
      { type: 'p', text: 'But once in a while, it opens up for others too.' },
      { type: 'h2', text: 'What is Loukáda?' },
      { type: 'p', text: 'It is not a festival. Not a lecture. Not an event with a schedule and a programme.' },
      { type: 'p', text: 'It is simple: you come, pick up a pitchfork or a shovel, help where it is needed — and along the way, there is talking. About animals. About what interests you. About life, nature, whatever is on your mind. Working with your hands does something to your head. It loosens it. It creates a space where conversation flows differently than in comment sections or behind office desks.' },
      { type: 'p', text: 'And if a dog trots up to your hand, a cat rubs against your leg, or the mouflon fawn comes over to inspect your boots — all the better.' },
      { type: 'h2', text: 'Next weekend, here at the meadow' },
      { type: 'p', text: 'We invite you to the meadow where the Nech mě růst project lives every day — not just on a screen, but in the physical world, in the mud, in the grass, in the care of animals who are here and who need attention and work.' },
      { type: 'p', text: 'Come and help. If you bring something good — for yourself, for others, or some suitable treats for the animals — we will be glad. But it is not a requirement. The only requirement is to arrive with a willingness to be somewhere different for a while.' },
      { type: 'h2', text: 'What awaits you' },
      { type: 'p', text: 'Mouflon fawn Yakul. One small mouflon. Tiny, adorable, and still slightly surprised by the world he arrived into. Watching him is reason enough to come. He carries that particular mix of shyness and curiosity that belongs to young animals — he approaches, stops, darts away, comes back. If you are patient and stay calm, he might come over to sniff your hand. That is an experience that is hard to put into words.' },
      { type: 'p', text: 'Cows. Large, calm creatures with an extraordinary memory for people. Once they know you, they will stand still and let themselves be stroked. Their calm is contagious. People who came to Loukáda for the first time told me that standing beside a cow was one of the most peaceful experiences they had had — and they had not expected anything like it.' },
      { type: 'p', text: 'Sheep. Loud, curious, and surprisingly social. They have their own rules, their own hierarchy, their own favourites. Watching them in the flock for a while is like reading a book written in a language you do not know, but somehow begin to understand.' },
      { type: 'p', text: 'Dogs and cats. They are everywhere. Always. They return love directly and without conditions.' },
      { type: 'h2', text: 'Why do we do this?' },
      { type: 'p', text: 'The Nech mě růst project is simple at its core: we believe that contact with nature and animals gives life a different dimension. That physical work has a value that cannot be fully replaced. That the silence of the meadow is rare and worth protecting — and sharing.' },
      { type: 'p', text: 'Loukáda is not about education or spreading any philosophy. It is a working gathering with a human face. You come, you work, you meet people, you meet animals, you eat something good. That is the whole plan.' },
      { type: 'p', text: 'And because each of us lives a slightly different life and is interested in different things — someone comes from the city, someone from the countryside, someone thinks about farming, someone about the digital world, someone simply wants a nice afternoon outside their usual environment — the topics of conversation arise on their own. Nobody sets them in advance.' },
      { type: 'h2', text: 'The meadow as a different kind of time' },
      { type: 'p', text: 'There is something you only learn when you work by hand beside a living creature.' },
      { type: 'p', text: 'The mouflon fawn does not care whether you are productive. The cow does not know if your tasks are done. The sheep will not give you feedback on your performance.' },
      { type: 'p', text: 'But they respond to your presence. To how you move, how you speak, how you breathe. There is a quiet lesson in that, hard to find elsewhere — learning to be where you actually are.' },
      { type: 'p', text: 'The meadow has its own time. And if you give yourself over to it, even for just one day, you will return home entirely calm.' },
      { type: 'h2', text: 'Practical information' },
      { type: 'p', text: 'Come next weekend. Wear something that can get dirty. Bring good spirits and perhaps something to eat or drink for a shared break — that always goes down well.' },
      { type: 'callout', text: 'If you would like to bring treats for the animals, a great choice is OvoZel from the nearby Jamboz farm. More at www.jamboz.cz' },
      { type: 'p', text: 'Loukáda is not a big thing. It is one afternoon, maybe a whole day. People come, they work, they talk, they leave. The animals stay — as always.' },
      { type: 'p', text: 'But such gatherings carry a weight that is hard to find elsewhere. Shared work, physical presence, contact with animals, with soil, with a rhythm we do not control — we carry that with us, even if we do not notice it at the time.' },
      { type: 'p', text: 'The Nech mě růst project exists because we believe this matters. That the meadow is a place worth coming to. That the mouflon fawn who comes to sniff your hand will tell you more than any weekend workshop.' },
      { type: 'quote', text: 'See you on the meadow.' },
    ],
    ru: [
      { type: 'p', text: 'Утро на лугу начинается раньше, чем просыпается большинство людей. Ещё до первого кофе нужно проверить ограды, принести сено, покормить поросят. Коровы стоят спокойно в своём ритме, овцы громко комментируют приход — без стеснения, собаки потягиваются в золотом свете. А где-то среди всего этого копошится маленькая, чуть неуверенная, чуть любопытная фигурка — наш муфлончик Якул.' },
      { type: 'p', text: 'Этот ритм здесь каждый день. Без исключений, без перерывов.' },
      { type: 'p', text: 'Но раз в какое-то время он открывается и для других.' },
      { type: 'h2', text: 'Что такое Loukáda?' },
      { type: 'p', text: 'Это не фестиваль. Не лекция. Не мероприятие с программой и расписанием.' },
      { type: 'p', text: 'Всё просто: приезжаете, берёте вилы или лопату, помогаете там, где нужно — и по ходу дела разговариваете. О животных. О том, что вас интересует. О жизни, о природе, о том, что сейчас занимает. Работа руками делает что-то с головой. Освобождает её. Создаёт пространство, в котором говорится иначе, чем в комментариях в соцсетях или за офисным столом.' },
      { type: 'p', text: 'А если при этом к руке прибежит ласковая Атилка, кошка потрётся о ногу или муфлончик подойдёт поближе и начнёт изучать ваши ботинки — тем лучше.' },
      { type: 'h2', text: 'Следующие выходные — у нас на лугу' },
      { type: 'p', text: 'Приглашаем вас на луг, где проект Nech mě růst живёт каждый день по-настоящему — не только на экране, а в физическом мире, в грязи, в траве, в заботе о животных, которые здесь есть и которым нужны внимание и труд.' },
      { type: 'p', text: 'Приезжайте помочь. Если привезёте с собой что-нибудь вкусное — для себя, для других, или подходящие лакомства для животных — будем рады. Но это не обязательно. Обязательно одно: приехать с желанием побыть немного в другом месте, чем обычно.' },
      { type: 'h2', text: 'Что вас ждёт' },
      { type: 'p', text: 'Муфлончик Якул. Один маленький муфлон. Крошечный, милый и всё ещё немного удивлённый миром, в который пришёл. Наблюдать за ним — само по себе повод приехать. В нём та особая смесь робости и любопытства, которая свойственна детёнышам: подходит ближе, останавливается, отскакивает, возвращается. Если у вас есть терпение и вы остаётесь спокойны — возможно, он придёт вас обнюхать. Это ощущение трудно описать словами.' },
      { type: 'p', text: 'Коровы. Большие, спокойные существа с невероятной памятью на людей. Как только они вас узнают, стоят смирно и позволяют себя погладить. Их спокойствие заразительно. Те, кто приезжал на Loukáda впервые, говорили мне, что постоять рядом с коровой — один из самых умиротворяющих опытов в их жизни. И они совсем этого не ожидали.' },
      { type: 'p', text: 'Овцы. Шумные, любопытные и удивительно социальные. У них свои правила, своя иерархия, свои любимцы и нелюбимцы. Понаблюдать за ними в стаде — всё равно что читать книгу на языке, которого вы не знаете, но почему-то начинаете понимать.' },
      { type: 'p', text: 'Собаки и кошки. Они везде. Всегда. Отдают любовь прямо и без условий.' },
      { type: 'h2', text: 'Зачем мы это делаем?' },
      { type: 'p', text: 'Проект Nech mě růst в основе своей прост: мы верим, что контакт с природой и животными придаёт жизни другое измерение. Что физический труд имеет ценность, которую нельзя полностью заменить. Что тишина луга редка и её стоит беречь — и делиться ею.' },
      { type: 'p', text: 'Loukáda — не про образование и не про распространение какой-либо философии. Это рабочая встреча с человеческим лицом. Приедете, поработаете, познакомитесь с людьми и животными, съедите что-нибудь вкусное. Вот и весь план.' },
      { type: 'p', text: 'А поскольку каждый из нас живёт немного по-своему и интересуется разным — кто-то приедет из города, кто-то из деревни, кто-то занимается фермерством, кто-то цифровым миром, кто-то просто ищет хороший день вне привычной обстановки — темы разговоров возникают сами. Никто не назначает их заранее.' },
      { type: 'h2', text: 'Луг как другое время' },
      { type: 'p', text: 'Есть кое-что, чему учишься только тогда, когда работаешь руками рядом с живым существом.' },
      { type: 'p', text: 'Муфлончику всё равно, продуктивны ли вы. Корова не знает, выполнены ли ваши задачи. Овцы не дадут вам обратной связи по вашей эффективности.' },
      { type: 'p', text: 'Но они реагируют на ваше присутствие. На то, как вы двигаетесь, как говорите, как дышите. В этом есть тихий урок, который иначе трудно получить — научиться быть там, где ты сейчас есть.' },
      { type: 'p', text: 'У луга своё время. И если вы ему подчинитесь, хотя бы на один день, вернётесь домой совершенно спокойными.' },
      { type: 'h2', text: 'Практическая информация' },
      { type: 'p', text: 'Приезжайте в следующие выходные. Оденьте что-нибудь, что можно испачкать. Возьмите с собой хорошее настроение и, если хотите, что-нибудь вкусное для общей паузы — это всегда радует.' },
      { type: 'callout', text: 'Если хотите привезти лакомства для животных — отличный вариант OvoZel с фермы Jamboz, которая находится неподалёку. Подробнее на www.jamboz.cz' },
      { type: 'p', text: 'Loukáda — не большое дело. Это один день, может быть полдня. Люди приедут, поработают, поговорят, уедут. Животные останутся — как всегда.' },
      { type: 'p', text: 'Но такие встречи имеют вес, который иначе трудно найти. Общий труд, физическое присутствие, контакт с животными, с землёй, с ритмом, которым не управляем мы — это остаётся с нами, даже если мы не осознаём этого в тот момент.' },
      { type: 'p', text: 'Проект Nech mě růst существует, потому что мы верим: это имеет смысл. Что луг — место, куда стоит приехать. Что муфлончик, который придёт обнюхать вашу руку, скажет вам больше, чем любой выездной семинар.' },
      { type: 'quote', text: 'Увидимся на лугу.' },
    ],
  },
},
  
  {
    id: 'emergent-prompting',
    slug: 'emergent-jak-spravne-promptovat',
    date: '2026-05-01',
    accent: '#9ae66e',
    readTime: 6,
    category: { cs: 'Nástroje', en: 'Tooling', ru: 'Инструменты' },
    title: {
      cs: 'Jak (skutečně) promptovat v Emergentu',
      en: 'How to (actually) prompt in Emergent',
      ru: 'Как (по-настоящему) промптить в Emergent',
    },
    excerpt: {
      cs: 'Emergent staví aplikace přímo z dialogu. Když mu mluvíš jako řemeslníkovi, postaví ti dílo. Tady je můj postup — a proč teď stojí jen dolar.',
      en: 'Emergent builds apps from conversation. Speak to it like a craftsman, and it will craft. Here is my way — and why it now costs just a dollar.',
      ru: 'Emergent строит приложения из диалога. Говори с ним как с мастером — и он построит. Вот мой способ — и почему он сейчас стоит всего доллар.',
    },
    body: {
      cs: [
        { type: 'p', text: 'Emergent je platforma, kde se v rozhovoru s AI rodí celé webové i mobilní aplikace. Já tady stavím tenhle web — a postavil bych si tu i ten příští. Není to magie. Je to pořádný řemeslník, který umí poslouchat.' },
        { type: 'h2', text: 'Co Emergent reálně umí' },
        { type: 'list', items: [
          'Frontend i backend v jedné konverzaci — React, FastAPI, MongoDB',
          'Deploy na Vercel nebo Netlify v podstatě jedním klikem',
          'Pamatuje si kontext celého projektu',
          'Refaktoruje, opravuje chyby, testuje',
          'Píše dokumentaci, README a deploy konfiguraci',
        ]},
        { type: 'h2', text: 'Jak s ním mluvit' },
        { type: 'p', text: 'Nech ho dělat to, v čem je dobrý — myslet samostatně. Tvoje práce není psát kód. Tvoje práce je vědět, co chceš. Pak to řekneš jasně, prostě a klidně. Jako řemeslníkovi, kterému věříš.' },
        { type: 'list', items: [
          'Začni vizí, ne detaily — řekni co a proč, ne jak',
          'Jeden záměr na zprávu — nemíchej tři přání dohromady',
          'Když něco selže, popiš co vidíš a co jsi čekal',
          'Schvaluj postup po krocích, ne po stovkách řádků',
          'Říkej "ne" často — AI si ráda přidá víc, než potřebuješ',
        ]},
        { type: 'h2', text: 'Cena, která dává smysl' },
        { type: 'callout', text: 'Aktuálně 1 $ / měsíc. Ano, doslova jeden dolar. Pro mě to znamená: zkus, co tě napadne. Postav. Pokus. Zahoď. Stavební papír je levný.' },
        { type: 'h2', text: 'Pojď to zkusit' },
        { type: 'p', text: 'Pokud chceš dát Emergentu šanci, použij odkaz níže — pomůžeš mi tím držet můj malý workflow naživu a sám si zahraješ s nástrojem, který opravdu staví.' },
        { type: 'cta', text: 'Otevřít Emergent', href: EMERGENT_AFFILIATE },
      ],
      en: [
        { type: 'p', text: 'Emergent is a platform where full web and mobile apps are born from a conversation with AI. I am building this site here — and I would build the next one here too. It is not magic. It is a proper craftsman who knows how to listen.' },
        { type: 'h2', text: 'What Emergent really does' },
        { type: 'list', items: [
          'Frontend and backend in one conversation — React, FastAPI, MongoDB',
          'Deploy to Vercel or Netlify in basically one click',
          'Remembers the entire project context',
          'Refactors, fixes bugs, tests',
          'Writes documentation, README and deploy config',
        ]},
        { type: 'h2', text: 'How to speak with it' },
        { type: 'p', text: 'Let it do what it is good at — thinking on its own. Your job is not to write code. Your job is to know what you want. Then say it clearly, simply, calmly. Like to a craftsman you trust.' },
        { type: 'list', items: [
          'Start with the vision, not the details — say what and why, not how',
          'One intent per message — do not mix three wishes together',
          'When something fails, describe what you see and what you expected',
          'Approve step by step, not hundreds of lines at once',
          'Say "no" often — AI loves to add more than you need',
        ]},
        { type: 'h2', text: 'A price that makes sense' },
        { type: 'callout', text: 'Currently 1 USD / month. Yes, literally one dollar. For me that means: try whatever crosses your mind. Build. Try. Throw away. The building paper is cheap.' },
        { type: 'h2', text: 'Come and try it' },
        { type: 'p', text: 'If you want to give Emergent a chance, use the link below — it helps me keep my little workflow alive and lets you play with a tool that really builds.' },
        { type: 'cta', text: 'Open Emergent', href: EMERGENT_AFFILIATE },
      ],
      ru: [
        { type: 'p', text: 'Emergent — платформа, где целые веб- и мобильные приложения рождаются из разговора с ИИ. Я строю этот сайт именно здесь — и следующий построил бы здесь же. Это не магия. Это настоящий мастер, умеющий слушать.' },
        { type: 'h2', text: 'Что Emergent реально умеет' },
        { type: 'list', items: [
          'Фронтенд и бэкенд в одном диалоге — React, FastAPI, MongoDB',
          'Деплой на Vercel или Netlify буквально в один клик',
          'Помнит контекст всего проекта',
          'Рефакторит, чинит ошибки, тестирует',
          'Пишет документацию, README и конфигурацию деплоя',
        ]},
        { type: 'h2', text: 'Как с ним говорить' },
        { type: 'p', text: 'Дай ему делать то, что он умеет — думать самостоятельно. Твоё дело не писать код. Твоё дело — знать, чего ты хочешь. И сказать это ясно, просто, спокойно. Как мастеру, которому доверяешь.' },
        { type: 'list', items: [
          'Начни с виденья, не с деталей — что и зачем, а не как',
          'Одно намерение на сообщение — не смешивай три желания',
          'Если что-то ломается, опиши что видишь и что ожидал',
          'Одобряй шаг за шагом, а не по сотням строк',
          'Говори "нет" часто — ИИ любит добавить больше, чем нужно',
        ]},
        { type: 'h2', text: 'Цена, в которой есть смысл' },
        { type: 'callout', text: 'Сейчас 1 $ / месяц. Да, буквально один доллар. Для меня это значит: пробуй всё, что приходит в голову. Строй. Пробуй. Выбрасывай. Строительная бумага дешёвая.' },
        { type: 'h2', text: 'Попробуй' },
        { type: 'p', text: 'Если хочешь дать Emergent шанс — пройди по ссылке ниже. Мне это поможет сохранить мой маленький рабочий поток, а ты поиграешь с инструментом, который действительно строит.' },
        { type: 'cta', text: 'Открыть Emergent', href: EMERGENT_AFFILIATE },
      ],
    },
  },
  {
    id: 'life-on-meadow',
    slug: 'zivot-na-louce-sto-dusi-ai-a-klid',
    date: '2026-05-01',
    accent: '#d4a45a',
    readTime: 5,
    category: { cs: 'Život', en: 'Life', ru: 'Жизнь' },
    title: {
      cs: 'Život na louce: sto duší, AI a klid',
      en: 'Life on a meadow: a hundred souls, AI, and stillness',
      ru: 'Жизнь на лугу: сто душ, ИИ и тишина',
    },
    excerpt: {
      cs: 'Žiju na louce s více než stovkou zvířat. Každý den je celodenní. A přesto mi technologie konečně začínají uvolňovat ruce.',
      en: 'I live on a meadow with more than a hundred animals. Every day is a full day. And yet, technology is finally freeing my hands.',
      ru: 'Живу на лугу с более чем сотней животных. Каждый день — на целый день. И всё-таки технологии наконец-то освобождают мои руки.',
    },
    body: {
      cs: [
        { type: 'p', text: 'Když ráno vstanu, první věc, kterou udělám, je obejít stáje. Více než sto duší — osel, ovce, muflon, slepice, husy, psi, kočky, krávy. Každá s vlastním jménem, charakterem a každodenní potřebou.' },
        { type: 'h2', text: 'Celý den krmení, voda, hlína' },
        { type: 'p', text: 'Žijeme v krajině, kterou jsme zdědili. Není to zoo, ani farma — je to společenství. Někteří jsou tady na konci své cesty, jiní teprve začínají. Společně neseme zodpovědnost. Voda, krmení, čištění, péče. Ráno, poledne, večer. Každý den.' },
        { type: 'p', text: 'K tomu se přidává starost o samotnou louku — sečení, vysazování, péče o stromy, ploty, dřevo. Není to romantika z Instagramu. Je to ohromná fyzická a soustavná práce.' },
        { type: 'h2', text: 'Sociální sítě a AI mezi stájemi' },
        { type: 'p', text: 'A přesto — nebo právě proto — řeším taky AI a digitální nástroje. Sociální sítě, web, projekty jako Nech mě růst, Impactly, ČSOP. Často mezi vyhazováním hnoje a šálkem čaje.' },
        { type: 'p', text: 'Dlouho mi přišlo, že mám dva životy. Jeden se zaprášenými botami a druhý před monitorem. Snažím se je uzavřít do jednoho dechu — louka i klávesnice ze stejné lásky.' },
        { type: 'h2', text: 'AI nám konečně uvolňuje ruce' },
        { type: 'callout', text: 'Konečně se dostáváme do fáze, kdy nám AI může opravdu pomoct. Nemluvím o náhradě člověka. Mluvím o tom, že mi to po deseti letech vrací několik hodin denně.' },
        { type: 'p', text: 'AI mi pomáhá psát příspěvky, plánovat, udržovat web v běhu, odpovídat na zprávy, ladit detaily. Ne místo mě — vedle mě, na pozadí. A já zatím můžu jít obejít koně.' },
        { type: 'p', text: 'Tohle je pro mě skutečný smysl technologií: ne připoutat člověka k obrazovce, ale uvolnit mu ruce pro to, co opravdu žije. Aby se mohl vrátit do trávy.' },
        { type: 'quote', text: '— Tony' },
      ],
      en: [
        { type: 'p', text: 'When I wake in the morning, the first thing I do is walk the stables. More than a hundred souls — donkey, sheep, mouflon, hens, geese, dogs, cats, cows. Each with its own name, its own temperament, its own daily need.' },
        { type: 'h2', text: 'All day: feed, water, soil' },
        { type: 'p', text: 'We live in a landscape we have inherited. Not a zoo, not a farm — a community. Some are at the end of their journey, others just beginning. Together we carry the responsibility. Water, feed, cleaning, care. Morning, noon, evening. Every day.' },
        { type: 'p', text: 'On top of that comes the meadow itself — mowing, planting, caring for trees, fences, wood. It is not Instagram romance. It is enormous, continuous physical work.' },
        { type: 'h2', text: 'Social media and AI between the stables' },
        { type: 'p', text: 'And yet — or precisely because of it — I also work with AI and digital tools. Social media, the website, projects like Nech mě růst, Impactly, ČSOP. Often between shovelling manure and a cup of tea.' },
        { type: 'p', text: 'For a long time it felt like I had two lives. One with dusty boots, one in front of a monitor. I am trying to close them into one breath — the meadow and the keyboard from the same love.' },
        { type: 'h2', text: 'AI is finally freeing our hands' },
        { type: 'callout', text: 'We are finally entering a phase where AI can truly help. I am not talking about replacing a human. I am talking about it returning to me, after ten years, several hours a day.' },
        { type: 'p', text: 'AI helps me write posts, plan, keep the site running, answer messages, fine-tune details. Not instead of me — beside me, in the background. And meanwhile I can go and check on the horses.' },
        { type: 'p', text: 'This, to me, is the real meaning of technology: not to chain a person to a screen, but to free their hands for what truly lives. So they can return to the grass.' },
        { type: 'quote', text: '— Tony' },
      ],
      ru: [
        { type: 'p', text: 'Когда я утром встаю, первое, что я делаю, — обхожу конюшни. Более ста душ: лошади, овцы, козы, куры, гуси, собаки, кошки, коровы. У каждого своё имя, свой характер, своя ежедневная нужда.' },
        { type: 'h2', text: 'Весь день: корм, вода, земля' },
        { type: 'p', text: 'Мы живём в ландшафте, который нам достался. Это не зоопарк и не ферма — это сообщество. Кто-то в конце своего пути, кто-то только начал. Вместе мы несём ответственность. Вода, корм, уборка, забота. Утро, полдень, вечер. Каждый день.' },
        { type: 'p', text: 'Ко всему этому — сам луг: косьба, посадки, уход за деревьями, заборами, дровами. Это не романтика из Instagram. Это огромная и постоянная физическая работа.' },
        { type: 'h2', text: 'Соцсети и ИИ между конюшнями' },
        { type: 'p', text: 'И всё же — или именно поэтому — я ещё занимаюсь ИИ и цифровыми инструментами. Соцсети, сайт, проекты вроде Nech mě růst, Impactly, ČSOP. Часто между уборкой навоза и чашкой чая.' },
        { type: 'p', text: 'Долго мне казалось, что у меня две жизни. Одна — в пыльных ботинках, другая — перед монитором. Я пытаюсь свести их в один вдох: луг и клавиатура из одной любви.' },
        { type: 'h2', text: 'ИИ наконец-то освобождает руки' },
        { type: 'callout', text: 'Мы наконец входим в фазу, где ИИ реально помогает. Я не говорю о замене человека. Я говорю о том, что он возвращает мне после десяти лет несколько часов в день.' },
        { type: 'p', text: 'ИИ помогает мне писать посты, планировать, поддерживать сайт, отвечать на сообщения, шлифовать детали. Не вместо меня — рядом, на фоне. А я тем временем иду проведать лошадей.' },
        { type: 'p', text: 'Для меня в этом и есть смысл технологий: не приковать человека к экрану, а освободить руки для того, что действительно живёт. Чтобы он мог вернуться в траву.' },
        { type: 'quote', text: '— Tony' },
      ],
    },
  },
];
